### ISSUE TITLE
`glasskube install --gitops` should exclude most `metadata`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1008]
**Is your feature request related to a problem? Please describe.**
When trying to use glasskube in a gitops approach by using `glasskube install [pkg] --dry-run -o yaml`, the output contains a `uid`, which probably should not be there. Same for `generation`, `managedFields` and others. 

**Describe the solution you'd like**
Probably all metadata fields except the `name` and `namespace` should be excluded from the output. 

**Describe alternatives you've considered**
None

**Additional context**
When trying to install a package this way via argocd, argo cannot sync because the uid field is immutable, but it would be changed.
When trying to directly apply the generated yaml with `kubectl`, it works, but the uid is changed.

**Comment by neehhaa06** [comment]
@christophenne 
> I think, First add a --prune-metadata flag to glasskube install that when set to true, excludes most metadata fields from the YAML output, keeping only name and namespace.

> Implementation

>  add --prune-metadata flag to glasskube install.
>  when flag is true, exclude these fields:

>       uid
>       generation
>       managedFields
>       creationTimestamp
>       resourceVersion
>        selfLink

    Keep name and namespace fields.

**Comment by christophenne** [comment]
@neehhaa06 thanks for your ideas, I also thought about treating this is a separate flag. That way it's still also possible to still get the "original" object if wanted for some reason.

However, since this is very gitops-oriented, I will just call the flag `--gitops` and it does the same as `--dry-run -o yaml` with additionally pruning the unwanted metadata.
