### ISSUE TITLE
Fix 2 Links in Roadmap 

### ISSUE THREAD

**Issue by thekubernaut** [glasskube/glasskube#103]
Fix the Links for CloudNative PG and Maria DB Operator in: https://glasskube.dev/roadmap#packages-and-apps-schedule
![Bildschirm­foto 2024-01-29 um 17 41 26](https://github.com/glasskube/glasskube/assets/130456438/8c9e41ac-671c-49d6-9f65-79218b758259)

**Comment by OmAximani0** [comment]
Hello @pmig @thekubernaut , 
I want to work on this. Can you please assign this to me ?

**Comment by pmig** [comment]
@OmAximani0  sure, go ahead
