### ISSUE TITLE
Glasskube should honor the KUBECONFIG environment variable

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#1040]
**Is your feature request related to a problem? Please describe.**
Almost every application in the "CLI for k8s" space allows using the `KUBECONFIG` environment variable to set the path to the kubeconfig file to use. Glasskube should follow suite and do the same.

**Describe the solution you'd like**
If the `KUBECONFIG` environment variable is set to a non-empty string, that value should be used for getting the kubeconfig. It should still be possible to overwrite this with the `--kubeconfig` flag though

**Comment by hanshal101** [comment]
I can work on this !!!

**Comment by kosmoz** [comment]
Hey @hanshal101, are you still working on #871? If not, I can assign this one to you and remove the other assignment. I hope you understand that, for fairness, we try to avoid assigning too many issues to individual contributors. :slightly_smiling_face:

**Comment by hanshal101** [comment]
Hey @kosmoz tbh I'm still figuring out on how to solve the 871. I think you can unassign me. Sorry for the inconvenience.

**Comment by Vivekgaddigi** [comment]
hey @kosmoz i would like to work on this

**Comment by bishalbera** [comment]
@Vivekgaddigi Hey are you still working on this? If not then I would like to try this :)

**Comment by Vivekgaddigi** [comment]
@bishalbera Go Ahead

**Comment by kosmoz** [comment]
@bishalbera noticed that this behavior is already implemented, so this issue can be closed.
