### ISSUE TITLE
`glasskube uninstall` should support `--dry-run`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1061]
**Is your feature request related to a problem? Please describe.**
Just as many other commands, `uninstall` should have a `--dry-run` option to simulate package uninstallation. 

**Additional context**
#629

**Comment by hanshal101** [comment]
can I work on this?

**Comment by christophenne** [comment]
Sure, go for it :)

**Comment by neehhaa06** [comment]
Hello @christophenne :)

fix: #1061

> Yes, the glasskube uninstall command should support the --dry-run option.

> Here is some logic for Implementing --dry-run in glasskube uninstall.

   ###  Parse: Recognize --dry-run, extract package name.

    Dependencies: Function to list dependencies.

    Simulate: Identify packages to be removed.

    Output: Display packages

    Integrate: Execute dry run if flag set, else uninstall.

    Test: Unit tests
