### ISSUE TITLE
Ingress-nginx package should support namespace scoped installation

### ISSUE THREAD

**Issue by botchk** [glasskube/glasskube#1070]
**Is your feature request related to a problem? Please describe.**
Some cluster architectures require multiple ingress controllers for better isolation and configuration of workloads. Nginx ingress also supports this use case and the glasskube package just needs to allow configuration of the underlying helm chart (https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/)

**Describe the solution you'd like**

* Change the scope of ingress-nginx package to namespace
* Introduce additional configuration values such as `ingressClass`. These are needed to manage multiple ingress controllers within the same cluster.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by yeahservice** [comment]
As discussed in Discord (https://discord.com/channels/1176558649250951330/1176558649762660476/1270049769078915147), I would also work on this.

**Comment by yeahservice** [comment]
These were the migration changes for quickwit https://github.com/glasskube/packages/pull/180; A migration notice was added to the description.

Although I am unsure about the notice in the release notes. The packages releases and glasskube releases are not linked?

**Comment by christophenne** [comment]
> I would prefer not having two different ingress-nginx packages and opt for a breaking change. 

I would also prefer the breaking change here.

> These were the migration changes for quickwit https://github.com/glasskube/packages/pull/180; A migration notice was added to the description.

Yes I think that would also be the preferred way to go here. 

> Although I am unsure about the notice in the release notes. The packages releases and glasskube releases are not linked?

No they are not directly linked. I think most of the times this isn't necessary, but it's true that sometimes installing a certain package requires some minimum glasskube version. Unfortunately we didn't do this yet: #353

**Comment by pmig** [comment]
I think we are good to go on this one. Feel free to ping us if any question arise.
