### ISSUE TITLE
UI version warning text should consider gitops mode

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1071]
**Is your feature request related to a problem? Please describe.**
The Glasskube UI shows a warning on top of the page, if client version and cluster version are not equal. It also shows a hint how to update the cluster version:

![Screenshot from 2024-08-05 11-09-27](https://github.com/user-attachments/assets/9dfd17b4-78c3-4267-b1bc-33c29ba6d048)

In GitOps mode however, running only `glasskube bootstrap` directly applies the newer manifests into the cluster, which will in the next reconciliation by argocd be replaced again by whatever is defined in the git repository. 

**Describe the solution you'd like**
The message in the UI should be different, if gitops mode is enabled in the cluster. It should be: "... Please update the cluster components to ... by using `glasskube bootstrap --dry-run -o yaml` and pushing the generated manifests into your gitops repository."

**Describe alternatives you've considered**
Completely remove the "Please upate..." sentence, but I think it's a nice hint.

**Additional context**

**Comment by Aryakoste** [comment]
Hello @christophenne I would like to work on this issue.

**Comment by aashikantkumar** [comment]
I  want to work on it ,please, can you assign the task ?

**Comment by jakepage91** [comment]
I've assigned it to @Aryakoste since they asked first 👍
