### ISSUE TITLE
`glasskube install` should respect `--namespace` flag

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1081]
**Is your feature request related to a problem? Please describe.**
Namespaced packages can be installed via `glasskube install [package-name]`, and then the namespace will be asked for. If one wants to install it without interactivity, `glasskube install [package-name] [namespace]` can be used. There is also a `--namespace` flag available at the install command, but it doesn't do anything. 

**Describe the solution you'd like**
It should also be possible to install a namespaced package by using `glasskube install [package-name] --namespace [namespace]`. If both options are used (argument and `--namespace` flag), there should be an error. 

**Describe alternatives you've considered**
Removing the `--namespace` flag, but I think it would be nice to make a command more clear. 

**Additional context**

**Comment by yeahservice** [comment]
> Namespaced packages can be installed via glasskube install [package-name], and then the namespace will be asked for.

This is currently behaves differently? E.g. running `glasskube install quickwit` will just ask for the package name, not the namespace name. The package is then installed in the default namespace

```
glasskube install quickwit

glasskube list --show-all
PACKAGENAME    NAMESPACE               NAME                    VERSION                        AUTO-UPDATE  REPOSITORY  STATUS
quickwit       default                 quickwit                v0.8.1+5                                    glasskube (used)  Failed
```

> There is also a --namespace flag available at the install command, but it doesn't do anything.
`glasskube install quickwit --namespace quickwit` will install it in the namespace `quickwit`
```
glasskube install quickwit --namespace quickwit

./dist/glasskube list --show-all
PACKAGENAME    NAMESPACE               NAME                    VERSION                        AUTO-UPDATE  REPOSITORY  STATUS
quickwit       default                 quickwit                v0.8.1+5                                    glasskube (used)  Failed  
quickwit       quickwit               quickwit-2             v0.8.1+5                                    glasskube (used)  Failed  

```

> If one wants to install it without interactivity, glasskube install [package-name] [namespace] can be used.
Also `glasskube install [package-name] [namespace]` ignores the namespace?
```
glasskube install quickwit quickwit-3

./dist/glasskube list --show-all
PACKAGENAME    NAMESPACE               NAME                    VERSION                        AUTO-UPDATE  REPOSITORY  STATUS
quickwit       default                 quickwit                v0.8.1+5                                    glasskube (used)  Failed  
quickwit       default                 quickwit-3             v0.8.1+5                                    glasskube (used)  Failed  
quickwit       quickwit               quickwit-2             v0.8.1+5                                    glasskube (used)  Failed  
```

**Comment by christophenne** [comment]
@yeahservice you are absolutely right with everything, closing this because it was nonsense and glasskube works as expected.
