### ISSUE TITLE
Install `glasskube-autoupdater` if a package with auto update enabled gets installed

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#1090]
**Is your feature request related to a problem? Please describe.**
We released the `glasskube-autoupdater` package. But it does not get automatically installed if a package with automatic updates is installed or automatic updates get enabled later on.

**Describe the solution you'd like**
We should place a warning / hint around the checkbox that in order for auto updates to work, the `glasskube-autoupdater` package needs to be installed. `glasskube-autoupdater` should be a link to the actual package.

**Describe alternatives you've considered**

**Additional context**

**Comment by bishalbera** [comment]
I can try this
