### ISSUE TITLE
Allow enable / disable auto updating for installed (cluster-)packages 

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#1091]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to change the status of package 

**Describe the solution you'd like**
Enable and disable auto updates via the UI.

**Describe alternatives you've considered**

**Additional context**
We will do this together with #1167

**Comment by Baalekshan** [comment]
@pmig can I take this. Although not marked as help wanted, I guess it could be worked on by contributors.

**Comment by pmig** [comment]
Hi @Baalekshan yes I you are right, we just need to set the Annotation to the (cluster)package similar as it is done for creation new pacakges. Feel free to write in our Discord if you run in any troubles.
