### ISSUE TITLE
CLI: Create namespace if necessary when installing a namespace-scoped Package

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#1101]
**Is your feature request related to a problem? Please describe.**
Installing a namespace-scoped package can be more complicated than necessary if the target namespace does not exist yet. In that case, a user has to resort to `kubectl` or other means to create the namespace before being able to install the package. This should not be necessary.

**Describe the solution you'd like**
When installing a namespace-scoped package, the CLI should check if the target namespace exists and, if it does not, create it after the user has confirmed the install operation (if no `--yes` flag is present) and before the `Package` is created. The installation summary should inform the user that the namespace is going to be created. Example output:

```
$ glasskube install quickwit -n test
Summary:
 * The following packages will be installed in your cluster (minikube):
    1. quickwit of type quickwit in namespace test (version v0.8.1+5)
 * Namespace test does not exist and will be created
 * Automatic updates will be not enabled
```

**Additional context**
For context, see #1084

**Comment by hanshal101** [comment]
Hey @kosmoz can I work on this ?

**Comment by kosmoz** [comment]
> Hey @kosmoz can I work on this ?

Sorry @hanshal101 I missed your comment. Are you still interested in tackling this issue?

**Comment by hanshal101** [comment]
Yes Sir !
