### ISSUE TITLE
Add support for ParadeDB

### ISSUE THREAD

**Issue by philippemnoel** [glasskube/glasskube#1125]
**Is your feature request related to a problem? Please describe.**
Hi guys! I'm one of the maintainers of https://github.com/paradedb/paradedb. We'd love for ParadeDB to be supported on Glasskube. You can find our Helm chart here, for reference: https://github.com/paradedb/helm-charts.

We're built on CloudNativePG with a few extra extensions that we build, so it should be nearly identical.

**Describe the solution you'd like**
^

**Describe alternatives you've considered**
N/A

**Additional context**
Happy to help whenever possible.

**Comment by codeknight03** [comment]
Hey @kosmoz is there a standard process for packages to follow to be onboarded onto glasskube ? I tried going through all the issues labelled with `packages` but did not find any of them closed. 

Any documentation I can refer to as a package maintainer and / or as a contributor to help in the process of onboarding new packages.

**Comment by kosmoz** [comment]
Hey there :slightly_smiling_face:  There is no "definitive" process, but we do have a [guide](https://glasskube.dev/guides/how-to-add-a-package/) on our website that documents the general steps based on an example. Generally, the steps would be something like:
1. Fork the GitHub repository `glasskube/packages` and check it out locally
2. Add then necessary files for the new package
3. Test the package locally
4. Submit a PR to the upstream repository

If anything is unclear we are happy to help via comments on GitHub or on our Discord.

**Comment by pmig** [comment]
closed by: https://github.com/glasskube/packages/commit/cb77a9e779e733cd6e544d4ba1f26f05ccce1940
