### ISSUE TITLE
Show package dependencies in CLI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#113]
The CLI should provide a way for the user to see which dependencies a package includes.

**Comment by hanshal101** [comment]
Hey is this issue open for now? If yes then I'll like to work on it.

**Comment by christophenne** [comment]
Hi @hanshal101, thanks for your interest, but I think all of the dependency management (#112) issues are too intertwined right now and kind of dependent/blocking on each other sometimes. Also it's the major feature for the upcoming release. This is why we want to rather keep those for ourselves for the core functionality. If there are additional issues in the future (and there will be for sure), we will describe those better and mark them as "help wanted" again. 

Off-Topic: Since you seem to be eager about working on Glasskube again (which we really appreciate!), I would suggest to take a look at #297.
