### ISSUE TITLE
Improve package detail page

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1167]
As shortly discussed, we want to have all input data in all cases in one form. 
* The labels of the package detail header will become part of the form. The package detail header then only shows the status (will have to be tried out how that looks, if there is only one label – TBD).
* When advanced options are enabled or the package is not installed, repo and version are changeable, otherwise they are read-only.
* Warnings about advanced options have to be adjusted and should be next to the two fields that can be changed, if enabled.
* The new "header" part of the form (containing repo, version and auto updates) will be in the same form as the configuration below.
* Header and config part of the form should be visibly separated, but it should be clear that the save/install button on the bottom is meant to be for the entire page. 

For that, the template and the endpoints will have to be refactored a bit, and maybe the advanced option information needs to be stored somewhere other then local storage?

Also, be aware that this might (?) affect the live reload of the package detail page (there is some logic whether only header or whole page should be refetched). 

From a technical point of view, it would be interesting to explore some options for more client-side interactivity (see input config component madness, namespace check, etc.).

Ref #1091

**Comment by prikshitsingh24** [comment]
@christophenne can I work on this issue?

**Comment by prikshitsingh24** [comment]
Any suggestions which issues I can go for
