### ISSUE TITLE
Show package components on UI and CLI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#1178]
**Is your feature request related to a problem? Please describe.**
The components introduced in #1126 are not visible yet to the user.

**Describe the solution you'd like**
The `describe` command and the package detail page should show the components, in a similar manner as done with the dependencies. On the UI we should also link to them: When the package is not installed, it should link to the "new" page for namespaced packages, and when it is installed, it should probably link to the page of the installed namespaced package. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Player1mene** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
