### ISSUE TITLE
Search bar overlaps an blocks the star counter on mobile devices 

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#1207]
**Describe the bug**
On mobile screen devices the newly added search bar now overlaps and covers the GitHub star counter component right beside it. 

**To Reproduce**
Open https://glasskube.dev on a mobile device (screenshot also added below)

**Expected behavior**
No overlap, usable search component as well as a visible star counter. 

**Screenshots**
![WhatsApp Image 2024-09-08 at 11 29 37 AM](https://github.com/user-attachments/assets/73123650-279a-4c90-995e-94f3bc571d94)

**Comment by prikshitsingh24** [comment]
@jakepage91  this issue can be closed since when i visit the website now it seems to be fixed
![WhatsApp Image 2024-09-20 at 06 36 50](https://github.com/user-attachments/assets/da541429-0cbd-4bd2-a9fe-900c53ec4bba)
