### ISSUE TITLE
Adjust blog image aspect ratio to adapt to different screen sizes

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#1208]
**Describe the bug**
On smaller screens the new blog appearance doesn't auto-adjust the image thumbnail aspect ratio, resulting in cut off border as can be seen in the screenshot attached below. 

**To Reproduce**
Open https://glasskube.dev/blog/ on a laptop screen

**Expected behavior**
Images adjust automatically to smaller screens and borders are not cut off

**Screenshots**
<img width="1507" alt="Screenshot 2024-09-08 at 11 07 57" src="https://github.com/user-attachments/assets/a75d39cd-143f-4e04-9b39-b77b3a020279">

**Comment by bishalbera** [comment]
Can I take this @jakepage91 ?
