### ISSUE TITLE
UI Revamp - Introduce htmx.org

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#126]
For the MVP we took some shortcuts to get the UI presentable quickly (e.g. no real build steps, full page reloads, duplicating templates and re-usable components, copying the CSS theme and inline style definitions). 

Before adding too many new features on top of this prototype, we should think about the UI in the long-term from a technology and architecture perspective, taking into account the upcoming features.  
* Do we want to continue with server-side rendered templates? If so, how do we manage more interactive use-cases?
* Do we need application state on the client?

This is to be decided and then implemented.

**Comment by pmig** [comment]
We can also have look at [`Masterminds/sprig`](https://github.com/Masterminds/sprig) to extend the default template functionality of Go.

**Comment by christophenne** [comment]
After tinkering with [htmx](https://htmx.org/) a bit, we decided to refactor the current quick-and-dirty UI solution with it to tackle the future challenges of the UI. Improvements done in this task will be:
* sub-templates / components for reusable UI parts - we'll stick to the builtin Go templates for now and maybe extend it with sprig when we need it
* avoid full-page reloads with htmx
* design more use-case specific endpoints instead of the one all-in-one endpoint we have right now - also in accordance with the hypermedia approach (see e.g. https://htmx.org/essays/10-tips-for-ssr-hda-apps/#tip-3-specialize-your-api-end-points)
* introduce websockets (using the htmx websockets extension) to push all kinds of serverside updates to the client (for now, needed for #164 - but also keeping in mind that future features might need such updates as well)

Right now we don't see a need for another JS-library, but if there should be cases in the future, where pure client-side interactivity is needed (i.e. a change on the UI that does not trigger anything on the backend), we could look into [alpine.js](https://alpinejs.dev/)
