### ISSUE TITLE
Add CLI-Flag to not await install/uninstall commands

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#133]
The CLI should have a consequent default behaviour for all commands that have some long-running operation in the background (like install, uninstall). This default behaviour (either wait or not-wait) should be changeable by the user with a command line flag. 

- [x] install command
- [ ] uninstall command

**Comment by christophenne** [comment]
related to #168 - both issues need to introduce a blocking `Uninstall` method, ideally this should only be done once.

**Comment by kosmoz** [comment]
Note that we currently do not enable [foreground deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion) for our owned resources. This would be necessary to make a blocking uninstall cmd useful.

**Comment by nitishfy** [comment]
I'd like to work on this!

**Comment by christophenne** [comment]
@nitishfy not 100% sure yet on the progress here, @jalavosus already started this one and has a draft-PR (unfortunately github won't let me assign him to the ticket right now).

Also, be aware of the dependency to #168 - it probably makes sense to finish #168 first.

We are preparing a couple new issues for contributors right now, we think it makes sense to pick one of those first.

**Comment by kosmoz** [comment]
Since the uninstall command is now blocking as well and both the installer and uninstaller offer a blocking and non-blocking action, it would make sense to implement this now.

@nitishfy, are you still interested in working on this?

**Comment by nitishfy** [comment]
> @nitishfy, are you still interested in working on this?
Hey, I might not have the bandwidth to work on this since I've other commitments aligned right now. Feel free to pickup this issue.

**Comment by kosmoz** [comment]
Alright, no worries! Thanks for letting us know.

**Comment by hanshal101** [comment]
Hey @kosmoz , I would like to work on this issue. Correct me if I am wrong till now, I understood that we need to create a flag detection (just for example) in CLI for setting the behavior of the operation. For example: if I want to run the process/operation in the background, I can use `glasskube install myapp -d` where `-d` represents daemon mode. And by default, it should wait for the operation to complete and then end the process/operation.

If this is correct, can you please guide me through the further steps that is intended to be taken.

**Comment by kosmoz** [comment]
Hi @hanshal101! 

The installer and uninstaller provide both blocking and non-blocking variants of their actions. So, for this ticket you would have to add the required bool flags to the install and uninstall commands (we already have some examples for this) and then call either the blocking or non-blocking variant of the action depending on the flag value. I would suggest calling those flags `no-wait`, since "waiting" is the default behavior for both commands. 

Please let me know if this is enough info for you to get started or if you have further questions.

**Comment by kosmoz** [comment]
Hi!

First, please use a bool flag instead, otherwise the usage would have to be `install --no-wait=no-wait` which is unnecessary.

Second, I think it should be as simple as 
```go
if cmdOptions.NoWait {
  installer.Install(...)
} else {
  installer.InstallBlocking(...)
}
```

**Comment by kosmoz** [comment]
Also, please create a PR with your proposed changes so we can review them properly

**Comment by hanshal101** [comment]
Ohh sorry will make these changes.

**Comment by hanshal101** [comment]
Hey @kosmoz should I add this as a feat commit.

**Comment by hanshal101** [comment]
Heyy, @kosmoz  , In the uninstall, I wonder if we need a go routine for the no-wait command.
