### ISSUE TITLE
Support keptn

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#137]

**Comment by OmAximani0** [comment]
Hi @christophenne , I want to contribute to this repository. Can you please tell is this issue beginner friendly and if yes can you please provide me some initial guide.
Thank you

**Comment by christophenne** [comment]
Hi @OmAximani0,
the keptn package will be supported with this PR: https://github.com/glasskube/packages/pull/16 - so for now there is nothing left to do here.
But we have a few other [good first issues](https://github.com/glasskube/glasskube/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), and we are working on adding some new ones :)

**Comment by OmAximani0** [comment]
Thank you @christophenne , I'll look for those other `good first issues`
