### ISSUE TITLE
Bug: Can't install cert-manager

### ISSUE THREAD

**Issue by thschue** [glasskube/glasskube#148]
When trying to install cert-manager via the UI and CLI, the app installation doesn't finish.

## Steps to reproduce
* Set up a new cluster (exoscale)
* Install Glasskube (`brew install glasskube/tap/glasskube`)
* Open UI and install cert-manager package or `glasskube install cert-manager`

## Expected result
* cert-manager gets installed

## Current result
cert-manager is not installed and fails after some time. It seems like the fqdn source-controller.flux-system.svc.cluster.local. is not reachable

## Additional Info
![image](https://github.com/glasskube/glasskube/assets/38893055/e4ff9157-a771-4138-85a2-a5e88f80735b)

**Comment by kosmoz** [comment]
Thank you @thschue for the report!

If I had to guess, I would say that the base domain of your cluster's Coredns is different from cluster.local. Could you please check this? You can usually run `kubectl get -n kube-system configmaps coredns --template="{{ .data.Corefile }}"` to inspect the Coredns file. There should be a line that looks like this:

```
kubernetes cluster.local in-addr.arpa ip6.arpa {
```
or like this:
```
kubernetes some-other-name.cluster.local in-addr.arpa ip6.arpa {
```

Please let me know if you have any questions!

**Comment by thschue** [comment]
As exoscale cluster's don't end with *.cluster.local this is the case ... But especially for this case, I think there should be a plan (like only using source-controller.flux-system.svc or overriding the default domain name) as this might lead to problems at some cloud providers.

**Comment by kosmoz** [comment]
Yes, that is a good point… I will investigate this further.
