### ISSUE TITLE
Hot reload for UI development

### ISSUE THREAD

**Issue by philipp65** [glasskube/glasskube#170]
I noticed that when changing something on the server code or in the UI templates, one has to restart the server every time in order for these changes to be applied. That's a bit tedious and bad for developer experience.

The dev stack should support hot reload without manual restarts. Otherwise cool project! :-)

**Comment by aatbip** [comment]
Can I work on this?

**Comment by pmig** [comment]
@aatbip sure go ahead!

**Comment by pmig** [comment]
@aatbip I think this issue is also related to #126 so we not proceeding on it atm. @aatbip

**Comment by christophenne** [comment]
This could be of interest: https://github.com/zachatrocity/htmx-hyperscript-starter

**Comment by OmAximani0** [comment]
@pmig @christophenne They are using [aarol/reload](https://github.com/aarol/reload) for hot reloading, but they are somethings which I think we should look at in the [aarol/reload#caveats](https://github.com/aarol/reload?tab=readme-ov-file#caveats) mentioned in there `README.md`

**Comment by pmig** [comment]
Hi @OmAximani0 this tasks definitely needs some exploration / prototyping / try you can come up with a working prototype and we can give you feedback on your solution
