### ISSUE TITLE
Show Package Details on separate page

### ISSUE THREAD

**Issue by erikauer** [glasskube/glasskube#172]
The package overview is great, but I'd like to see a more detailed description to the packages and additional information like links to the website or github. I would expect a separate detail page for each package that can be entered from the overview.

**Comment by aatbip** [comment]
I want to take on this issue.

**Comment by pmig** [comment]
@aatbip  sure. If there is a need to extend the package manifest we are happy to go over your suggestions.

**Comment by pmig** [comment]
@aatbip sadly this issue is also related to #126 which we need to tackle first in order to proceed with this one, please feel free to select another issue from this list: https://github.com/glasskube/glasskube/labels/help%20wanted
