### ISSUE TITLE
Automatic Bootstrap in CLI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#196]
**Is your feature request related to a problem? Please describe.**
If glasskube is not bootstrapped, any CLI command (except for `serve`) shows an error message with the command that the user needs to execute manually.

**Describe the solution you'd like**
In such a case, it would be easier for the user when the CLI command asks the user whether glasskube should be bootstrapped, along with the information that it is not bootstrapped yet. Something like the message we currently have, and additionally the Yes/No promt (which already exists in `cliutils`) to have the user input his decision.

This should be done for all commands that currently only show the error message, but e.g. not for the `serve` command. 

**Additional context**
Related #123 #149

**Comment by UtkarshUmre** [comment]
i would like to work on this issue

**Comment by pmig** [comment]
Hi @UtkarshUmre as you are already assigned to https://github.com/glasskube/glasskube/issues/81 I will leave this ticket unassigned for now.

**Comment by pmig** [comment]
as discussed on discord, reassigning  now

**Comment by pmig** [comment]
@UtkarshUmre are there any updates from your side on this issue?

**Comment by UtkarshUmre** [comment]
Hey @pmig I'll soon provide updates on this. Currently, I'm working on this [issue](https://github.com/glasskube/operator/issues/462) and simultaneously trying to understand it. Once I encounter any problems, I'll update you
