### ISSUE TITLE
Support svg images via `iconUrl` of package manifest

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#206]
**Is your feature request related to a problem? Please describe.**
We needed to fix @thschue contribution for [@keptn](https://github.com/keptn) due to the fact that ui is not yet able to display svg images. The svg is not visible in the UI.

**Describe the solution you'd like**
Also support `iconUrl`s that link to an svg.

**Additional context**
Once we fixed this issue we can revert following commit: https://github.com/glasskube/packages/commit/2037ef97a2a655915b11724d548b2f692fd566b4

**Comment by p1kalys** [comment]
Hey @pmig, I would like to work on this issue, please assign it to me.

**Comment by p1kalys** [comment]
I think the reason for SVG incompatibility will be issues in Backend processing of images or incorrect MIME types or maybe other security restrictions where Browsers often have security restrictions in place that prevent the rendering of external resources, including SVG images, especially if they are loaded from untrusted sources or served over insecure connections.

Solution:
Inspect the source code to see how SVG rendering is handled. Look for any specific components, methods, or configurations related to SVG usage. Modify code to handle SVG iconUrls for contributions, update backend logic for SVG validation, and integrate frontend to render SVG images. Test thoroughly, document changes, and communicate updates. Finally, revert temporary fixes after confirming the solution works.
