### ISSUE TITLE
Client is outdated detection 

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#210]
**Is your feature request related to a problem? Please describe.**
Currently there is no hint that a new version of glasskube got released, so users might miss the latest features of Glasskube.

**Describe the solution you'd like**
 - An internal version util should be created that is able to fetch the latest version from the hour website.
 - For the GUI there should be an element in nav bar that hints that a new version is available
 - For the CLI we should print a warning that looks something like:
 

>  ```
> $ glasskube ls
>     --------------------------------------------------------------------------------------------------------------- 
>                                                                                                                     
>                                             Update available 0.0.1 → 0.0.2                                          
>                                Please update glasskube to the latest version                                     
>
>     --------------------------------------------------------------------------------------------------------------- 
> 
> NAME                  STATUS         
> cert-manager          Pending          
> cyclops               Not installed    
> ingress-nginx         Not installed    
> keptn                 Ready            
> kubernetes-dashboard  Ready  
> 
> ```

**Describe alternatives you've considered**
We could host a static file either 

**Additional context**
related to https://github.com/glasskube/glasskube/issues/205
depends on: https://github.com/glasskube/glasskube/pull/209

**Comment by Baalekshan** [comment]
@pmig  as you mentioned the internal version util should fetch the latest version from the hour website, could you make it more clear or provide a link to that .

**Comment by pmig** [comment]
Sure @Baalekshan thanks for asking the latest version number 
can be downloaded at: https://glasskube.dev/release.json

**Comment by OmAximani0** [comment]
Hello @pmig , Can it be a flag or it should run automatically every time ? Like we can add `version` flag where it shows current version of CLI tool and also if new version is available.

**Comment by pmig** [comment]
Hi it can run every time, on the serve and list command (as these commands take longer or have an external network request anyway), but fail silently, if there was a network error or timeout.

**Comment by pmig** [comment]
I thought a little longer about it we can run it automatically every time as the install command is now also blocking by default

**Comment by pmig** [comment]
Yes exactly

**Comment by Baalekshan** [comment]
I would like to work on this.
