### ISSUE TITLE
Add footer to the GUI

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#232]
**Is your feature request related to a problem? Please describe.**
We could a footer section in our UI displaying the version and also indicating if a new version is available.

**Describe the solution you'd like**
It could just be div with a gray small centered text (no boxes, nothing)

**Describe alternatives you've considered**
a bulkier footer.

**Additional context**
The GitHub footer actually looks nice
related to #210

**Comment by yyujinparkk** [comment]
Can I work on this issue?

**Comment by pmig** [comment]
Hi @yyujinparkk sure!

**Comment by Aryakoste** [comment]
Hello @christophenne @pmig. I would like to work on this issue.

**Comment by pmig** [comment]
Sure if you need any support, join our discord. As you probably already saw, we are using bootstrap and htmx :-)
