### ISSUE TITLE
`bootstrap` command not working for development builds

### ISSUE THREAD

**Issue by yrs147** [glasskube/glasskube#240]
**Describe the bug**
  I tried setting up glasskube in my local have been getting this error when I run the bootstrap command using the binary .
  

**To Reproduce**
1. Clone the project
2. Run the `make` command
3. Go to the `dist` directory
4. Run the command `./glasskube bootstrap`

**Expected behavior**
Bootstrapping should be working as expected

**Screenshots**
![image](https://github.com/glasskube/glasskube/assets/98258627/6dca4d56-beee-472a-aecf-40f829c022c5)

**Cluster Info (please complete the following information):**
 - Type: kubernetes
 - Version: 1.27
 - Provider: Minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: [e.g. v0.0.1]
 - CLI version: [output of `glasskube --version`]

**Additional context**

**Comment by pmig** [comment]
As commented in the related [Discord Thread](https://discord.com/channels/1176558649250951330/1206459682793721876). 


> At the moment bootstrapping only works with release versions. you could either set your local version to 0.0.2 or bootstrap glasskube from the last release version.

**Comment by kosmoz** [comment]
Another option is to copy the Manifest URL from the latest release and apply it using the `--url` flag, i.e. `glasskube bootstrap --url=xxx`.

However I agree that this is annoying and should be fixed.

**Comment by yrs147** [comment]
@pmig can I work on this ?

**Comment by kosmoz** [comment]
Hi @yrs147! Yes, you can work on this if you'd like!

The solution we though would be appropriate here would be adding a `--latest` flag to the `bootstrap` cmd. If this flag is set, rather than bootstrapping the currently installed version, the CLI should fetch `https://glasskube.dev/release.json` (see `checkforupdate.go`) and bootstrap the resulting version.

The `--latest` flag is false by default in a production build but `true` in a dev build. To make this distinction, one could check if the `config.Version` is equal to "dev" or something like that.

Do you think you could do that?

**Comment by kosmoz** [comment]
Or, if you have a different idea, let us know!

**Comment by yrs147** [comment]
Sure @kosmoz , would like to give this a try first , will get back if stuck somewhere

**Comment by kosmoz** [comment]
Hi @yrs147! Are you still working on this issue?

**Comment by yrs147** [comment]
Hey @kosmoz ! was busy with my exams , will be completing this now and raise a PR soon .

**Comment by pmig** [comment]
hi @yrs147,

As this issue gets more pressing we have been wondering if you have already started? Else we would re-assign it

**Comment by yrs147** [comment]
Hey @pmig 
I have completed the fix but for some reason I am unable to commit , looking into it at the moment
<img width="1077" alt="image" src="https://github.com/glasskube/glasskube/assets/98258627/63bcae3e-8ce2-43d0-aa50-91d6db3800d5">
<img width="1707" alt="Screenshot 2024-03-12 at 8 44 20 PM" src="https://github.com/glasskube/glasskube/assets/98258627/b3c36f19-e7d2-4851-b64c-f6efd2d71ba5">
