### ISSUE TITLE
`glasskube describe` command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#241]
**Is your feature request related to a problem? Please describe.**
We are working on the package detail page on the UI (#172 ), so there should be an equivalent command for the CLI to show all relevant package details. Just like on the UI, this should work for both uninstalled and installed packages, and the status of the package should be shown. 

**Describe the solution you'd like**
`glasskube describe [package-name]` should print the same package details to the console as we show in the UI. 

**Additional context**
Depends on #172 to develop the client functionality that can be used by both layers. 

For implementing this task, reuse `DescribePackage` from `pkg/describe/describe.go`, which contains all the logic to fetch all the relevant data which should be displayed.

**Comment by bishal7679** [comment]
Hey @christophenne Would like to give it a try!

**Comment by christophenne** [comment]
Hi @bishal7679, 
I think this issue is too dependent on #172 right now, which is still in progress. Also it would have to be speced in more detail. So I suggest you either wait until these tasks are done, or if you'd like, check out some other issues labeled with "help wanted" or "good first issue" - any help is appreciated :) Thanks!

**Comment by bishal7679** [comment]
Np @christophenne 
Will look into another issues :+1:

**Comment by christophenne** [comment]
@bishal7679 since the #172 is about the be closed soon, you could work on the describe command. Are you still interested?

**Comment by christophenne** [comment]
@bishal7679 thanks! I provided some additional information in the description above, if you need anything else, don't hesitate to ask here or on discord.

**Comment by bishal7679** [comment]
> @bishal7679 thanks! I provided some additional information in the description above, if you need anything else, don't hesitate to ask here or on discord.

Yeah! I'm getting my hands dirty with it and will let you know further update 
Thank you!

**Comment by christophenne** [comment]
Hi @bishal7679, I hope you are doing well. I just wanted to check in and ask how you are doing with this issue. Is there anything we can help you with? If so, please don't hesitate to reach out.

**Comment by bishal7679** [comment]
@christophenne I really apologize!
I wrapped up with my exams and didn't get to it!
But I will soon start working on it and will come with update

**Comment by christophenne** [comment]
@bishal7679 no worries! Thanks for letting us know, please have a quick look in Discord so we can synchronize on how we proceed.
