### ISSUE TITLE
Show Pending status during uninstallation on UI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#252]
**Is your feature request related to a problem? Please describe.**
On the UI, when uninstalling a package, we immediately show "Install" again, no matter how long the uninstallation takes. When clicking install again afterwards, the system can run into errors because the package has not been properly uninstalled yet.

**Describe the solution you'd like**
The UI should show "Pending" or something similar, until the uninstallation is done. This depends on the blocking uninstall we should get from issues #133 / #168.

**Describe alternatives you've considered**
None

**Additional context**
Depends on #133 / #168.

**Comment by Nishantkumar012** [comment]
Please assign this issue to me

**Comment by Nishantkumar012** [comment]
Hey @christophenne I can work on this

**Comment by christophenne** [comment]
Hi @Nishantkumar012, this can not be worked on yet, the two depending issues are not done yet. 
There are a few other open issues labeled with "good first issue" or "help wanted" – any contribution is appreciated :) Thanks!

**Comment by christophenne** [comment]
This has been implemented with the changes in #269 ("watch loop"/informer)
