### ISSUE TITLE
Add `version` command to glasskube

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#254]
**Is your feature request related to a problem? Please describe.**
A version command comes in handy to get the version of all glasskube components

**Describe the solution you'd like**
Similar to [flux version command](https://github.com/fluxcd/flux2/blob/main/cmd/flux/version.go#L157):

```shell
$ flux version
flux: v2.2.3
distribution: flux-v2.2.3
helm-controller: v0.37.4
kustomize-controller: v1.2.2
source-controller: v1.2.4
```

A glasskube version command could look like

```shell
$ glasskube version
glasskube: v0.0.3
package-operator: v0.0.2
```

If the glasskube deployment could not be found an error message should be printed:

> ✗ no deployments found in the glasskube-system namespace

**Additional context**
As linked above flux parses image name and tag and prints it in a list. We could to the same which would result in the needed result.  Also the `glasskube -v` command does not need to change.

This issue is related to #210 and can help #205

**Comment by Baalekshan** [comment]
I like to take this

**Comment by pmig** [comment]
Happy to hear this, please go ahead.

**Comment by pmig** [comment]
Hi @Baalekshan I just wanted to know if you have any questions regarding this ticket or need additional help?

**Comment by Baalekshan** [comment]
@pmig yeah, in flux there is choice to return the version as yaml or json is it needed here.

**Comment by pmig** [comment]
@Baalekshan no printing the version as described in the ticket is sufficient. As flux does it looks at the image tag of the package-operator deployment.
