### ISSUE TITLE
Error while building `glasskube` locally on go version `1.22`

### ISSUE THREAD

**Issue by OmAximani0** [glasskube/glasskube#266]
**Describe the bug**
When building the `glasskube` locally with go version of `1.22` it fails and gives the error shown in screenshot below

**To Reproduce**
1. Clone the repo
2. Run `make`
3. See error

**Expected behavior**
`glasskube` should support the latest stable go version `1.22`

**Screenshots**
![Screenshot from 2024-02-17 20-07-56](https://github.com/glasskube/glasskube/assets/75031769/5f312161-506f-4433-a98f-8d0d0d3b3f28)

**Additional context**
I downgraded my go version to `1.21.7` and its working fine

**Comment by kosmoz** [comment]
Hi @OmAximani0, thanks for reporting this!

We haven't switched to 1.22 yet and it is recommended to use 1.21.7 for development for the time being.

With that said, from your screenshot it looks like the error happens in `controller-gen`. Can you please try deleting the `bin` directory in your project and running `make` again?

**Comment by OmAximani0** [comment]
Hey @kosmoz , I tried by deleting `controller-gen` and run make again but it still fails and gives the same error

**Comment by kosmoz** [comment]
Okay, thank you! I created a PR that should fix this issue: #279

I also created #278 so we can track compatibility with the new Go version to make the transition easier once we think the time has come.
