### ISSUE TITLE
Show current context in uninstall command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#270]
**Is your feature request related to a problem? Please describe.**
The uninstall command does not show the current kube context to the user. 

**Describe the solution you'd like**
At the prompt "... Are you sure? (y/N)" there should be an additional hint about which cluster is being used. The prompt should be "[package] will be removed from your cluster ([context-name]). Are you sure? (y/N)"

**Describe alternatives you've considered**
None

**Additional context**
The name of the current context is available from the raw config of the context of the command (`client.RawConfigFromContext(cmd.Context())`). Of this raw config, the `CurrentContext` should be used.

**Comment by rafiramadhana** [comment]
can I work on this? thanks
