### ISSUE TITLE
Show current context in install command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#271]
**Is your feature request related to a problem? Please describe.**
The install command does not show the current kube context to the user. 

**Describe the solution you'd like**
Like in the uninstall command, there should be a prompt to ask the user whether they really want to install the given package to the given cluster. The prompt should be "[package] will be installed into your cluster ([context-name]). Are you sure? (y/N)"

**Describe alternatives you've considered**
None

**Additional context**
Also see #270

**Comment by UtkarshUmre** [comment]
i want to work on this
