### ISSUE TITLE
Parallelize `IsBootstrapped` function

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#285]
**Is your feature request related to a problem? Please describe.**
`pkg/bootstrap/validate.go:IsBootstrapped` function checks whether the two necessary custom resource definitions are available in the cluster. The `crdExists` function is called two times in sequence, but this could easily be done in parallel instead.

**Describe the solution you'd like**
Check the two CRDs in parallel.

**Comment by hanshal101** [comment]
Hey @christophenne I would like to work on this issue. Can you please assign me.

**Comment by hanshal101** [comment]
From the above code I have understood that we need to run the `crdExists` function parallelly for both `pkgsExist` and `pisExist` So to make this happen we need to make use of go routines.
Here we need to modify this code:https://github.com/glasskube/glasskube/blob/main/pkg/bootstrap/validate.go#L19-L27
```
pkgsExist, err := crdExists(ctx, cs, "packages")
	if err != nil {
		return false, err
	}
	pisExist, err := crdExists(ctx, cs, "packageinfos")
	if err != nil {
		return false, err
	}
	return pkgsExist && pisExist, nil
```

The modified code should somewhat looks like this:
```
var wg sync.WaitGroup
    wg.Add(2)

    var pkgsExist, pisExist bool
    var pkgsErr, pisErr error

    go func() {
        defer wg.Done()
        pkgsExist, pkgsErr = crdExists(ctx, cs, "packages")
    }()

    go func() {
        defer wg.Done()
        pisExist, pisErr = crdExists(ctx, cs, "packageinfos")
    }()

    wg.Wait()

    if pkgsErr != nil {
        return false, pkgsErr
    }
    if pisErr != nil {
        return false, pisErr
    }

    return pkgsExist && pisExist, nil
```

These are the required changes according to me. Please review them and suggest me if any changes needed.
Thank You.

**Comment by hanshal101** [comment]
Ohk well should I open a PR and make the necessary changes?

**Comment by christophenne** [comment]
Yes, please.

**Comment by hanshal101** [comment]
Hello @christophenne I have made the PR but it shows `Check commit message format / commit-lint (pull_request)` failed on checks. Please guide me on this failure.

**Comment by christophenne** [comment]
@hanshal101 the commit message should follow the conventional commits, so in your case that could be `feat(client): parallelize IsBootstrap function`. Please change your commit message to something like that and then force-push on your branch.

**Comment by christophenne** [comment]
Also see https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md#commit-message-format

**Comment by hanshal101** [comment]
`feat(client): parallelize IsBootstrap function` so this should be my commit message?

**Comment by hanshal101** [comment]
Hey @christophenne I have made the necessary changes. You can now merge this PR.

**Comment by christophenne** [comment]
@hanshal101 no worries, thanks for contributing!
