### ISSUE TITLE
Show whether a package is auto-updated

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#296]
**Is your feature request related to a problem? Please describe.**
`glasskube describe` command and the package detail page do not show yet whether a package is marked for auto updates.

**Describe the solution you'd like**
Show whether auto updates are enabled at a package or not. This should be done for both CLI (ls and describe command) and UI (package detail page).

Packages are marked for auto updates if they have a label `packages.glasskube.dev/auto-update` with value `true`.

**Describe alternatives you've considered**

**Additional context**
Ref #338 #341

**Comment by Baalekshan** [comment]
@christophenne can this issue be worked on now?

**Comment by christophenne** [comment]
@Baalekshan yes, do you want to take it?

**Comment by Baalekshan** [comment]
Yes

**Comment by christophenne** [comment]
reopening because UI part is not done

**Comment by Baalekshan** [comment]
@christophenne  I am working on this
