### ISSUE TITLE
Show entrypoints in `glasskube describe`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#297]
**Is your feature request related to a problem? Please describe.**
The user doesn't see which entrypoints an installed package has.

**Describe the solution you'd like**
Show the entrypoints of the installed manifest and the hint that these can be opened with `glasskube open`.
In the describe command, the installed manifest is already being used to display some information. The goal of this ticket is to also display a list of entrypoints, which are stored in the manifest. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hanshal101** [comment]
Hey @christophenne here what more should I add. According to me I should add the `Port`,`ServiceName`,`LocalPort` etc.

**Comment by christophenne** [comment]
@hanshal101 for each entrypoint the name (if existing) of the entrypoint, its service name, port and local port (if existing) should be printed

**Comment by hanshal101** [comment]
Ohk I'll work on this issue.
