### ISSUE TITLE
Prevent accidental bootstrapping of an older package-operator version

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#304]
**Is your feature request related to a problem? Please describe.**
If the latest newer version of the package operator is installed in the Kubernetes cluster the `bootstrap` command should just get executed, which will lead to a breaking change.

**Describe the solution you'd like**
Add a confirmation input [y/N] and ask the user if he is sure that we wants to downgrade the package-operator and potentially break the system.

**Describe alternatives you've considered**
Completely disallow it.

**Additional context**
This ticket is related to: #205
It is still possible install a specific manifest via the `--url`  flag.

**Comment by bhavyastar** [comment]
I would like to work on this issue. @pmig

**Comment by pmig** [comment]
Yes sure, please go ahead.

**Comment by pmig** [comment]
@bhavyastar  I just quickly wanted to check in, if you are still interested in working on this issue?

**Comment by bhavyastar** [comment]
Yes, I am working on this issue.

**Comment by christophenne** [comment]
We are opening up this issue to the community again, due to inactivity. Hope that's okay for you!

**Comment by hanshal101** [comment]
Hey @pmig I would like to work on this issue.

**Comment by hanshal101** [comment]
So here if I am not wrong here we only have to add the `Yes | No` prompt in the `cmd\glasskube\cmd\bootstrap.go`
