### ISSUE TITLE
Check if port 3000 is already in use

### ISSUE THREAD

**Issue by berendt** [glasskube/glasskube#306]
It is assumed that port 3000 can be used in the forwarding. In my case, however, a Docusaurus process is already running on port 3000. An error should occur at this point or another port should be used. Instead, the browser was simply opened on port 3000 (where Docusaurus was running)

```
ui	 |I| Forwarding from 127.0.0.1:3000 -> 80
```

**Comment by pmig** [comment]
Which version of Glasskube have you tested? 

**tldr:**

> We are actually doing it already, but the Docusaurus (node) webserver is a specific case.
> It binds on all interfaces and not only on localhost, but we don't want to on all network interfaces for security purposes.


_You can read about the full technical details in the original pull request review comment: https://github.com/glasskube/glasskube/pull/208#discussion_r1481948763_

**Comment by berendt** [comment]
Tested with

```
$ glasskube --version
glasskube version 0.0.3
```

**Comment by kosmoz** [comment]
Hi @berendt, thank you for your report! As @pmig already mentioned, such a check is already in place, although the error is not really propagated to the UI yet.

I just tried the same (also running a docusaurus dev server in the background) and got the correct error message:
```
could not open cyclops: could not open entrypoint ui: tcp port 3000 is not free
```

Could you please try to reproduce this bug again and then run `netstat -ntlp`. The output could be very helpful for us.

**Comment by kosmoz** [comment]
Another issue that can happen in this situation is that the browser still has a cached version of the other site. This can happen even if the docusaurus dev server is no longer running. Reloading the page once usually resolves this issue.

**Comment by christophenne** [comment]
@berendt we are closing this issue now, if it still persists feel free to open again.
