### ISSUE TITLE
Don't display outdated warning if a new version of a package is installed than the latest version

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#329]
**Is your feature request related to a problem? Please describe.**
If a new version of a package is installed than the `latestVersion` defined in the `package.yaml` the update warning gets displayed, but this is incorrect.

**Describe the solution you'd like**
Be aware of semantic versioning and only display the warning if applicable.

**Describe alternatives you've considered**
An alternative warning / note can be displayed if a newer version is installed.

**Additional context**
Related to: https://github.com/glasskube/glasskube/issues/308
Depends on: https://github.com/glasskube/glasskube/issues/311

**Comment by hanshal101** [comment]
Hey, I would like to work on this issue. Can you please guide me to recreate this scenario.

**Comment by christophenne** [comment]
Hi, I think right now this is too intertwined with our work on the dependency management #112. The logic whether we show the outdated warning or not will have to be adapted and we would run into too many conflicts.

**Comment by kosmoz** [comment]
Done in https://github.com/glasskube/glasskube/pull/401 and https://github.com/glasskube/glasskube/pull/404
