### ISSUE TITLE
Display installed version of a package in the UI

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#330]
**Is your feature request related to a problem? Please describe.**
It is not possible to determine which package is currently installed via the UI.

**Describe the solution you'd like**
- Similar to the `list`  command the installed version of a package should be displayed on the overview and detail page.
- On the detail page also display the latestVersion.
- If an update is available display the update path e.g. `v0.0.1` -> `v0.0.2`

**Describe alternatives you've considered**
Also always display the latest version.

**Comment by pmig** [comment]
Nice to hear that :-) for these kind of issues it always helps to also include a screenshot in the PR once it is done :-)

**Comment by hanshal101** [comment]
Hey @pmig I am getting the UI as the below image as I am using my local development mode i.e 

`go run main.go serve`

![image](https://github.com/glasskube/glasskube/assets/122217807/6c1106dd-56d7-4b7d-859f-88541acf85a8)


Please guide me through this issue

**Comment by hanshal101** [comment]
Do I need to run any additional command to install the packages.

**Comment by christophenne** [comment]
@hanshal101 you need to run `make web` to download the theme into your local environment. We should document this somewhere.
