### ISSUE TITLE
Package Updates in GitOps installation

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#339]
**Is your feature request related to a problem? Please describe.**
When Glasskube is used in the GitOps approach (i.e. some git repository holds the desired `Package` custom resources), the users do not get notified when there is an update to on of their packages. 

**Describe the solution you'd like**
Glasskube should offer some tool to open Pull requests in this Git repository, where package versions are updated, similar to what renovate/dependabot do. 

**Describe alternatives you've considered**

**Additional context**
This idea originated when implementing #311, where we decided to do auto-updates in a different way (i.e. Packages always need to have `Spec.Version` set.

**Comment by pmig** [comment]
This will be possible with: https://github.com/renovatebot/renovate/issues/29322

**Comment by pmig** [comment]
Already implemented
