### ISSUE TITLE
Mandatory Package Version

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#341]
**Is your feature request related to a problem? Please describe.**
In #311 we found that the auto-updating process handling is not the correct way to approach this. Instead we want a separate component (operator) doing such updates by patching the Package version, instead of the package to have an empty version. See also #338. 

**Describe the solution you'd like**
Because of this change, the Package Version should be mandatory in the schema, and consequently all places where the Package Version is being used (operator, CLI, UI) must be refactored to the new logic. A package that should be auto-updated should get a label "glasskube/auto-updated". A package with such a label will then be picked up by the new controller (#338). 

Documentation must be updated too.

**Describe alternatives you've considered**
None

**Additional context**
See #311, #338

**Comment by hanshal101** [comment]
Hey, I would like to look into this issue. Can you please describe this in more detail?

**Comment by christophenne** [comment]
Hi, this is already assigned and in progress.
