### ISSUE TITLE
No error message in UI when opening entry-point fails

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#354]
**Describe the bug**
Opening a package entry-point can fail for a multitude of reasons, but in no case we display an error message in the UI.

**To Reproduce**
0. Open UI
1. Install a package that has an entrypoint (e.g. cyclops)
2. Stop the package-operator
3. Delete all deployments in the package namespace
4. Click "open"

**Expected behavior**
An error message that no pod is ready to handle the entrypoint.

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.28.3
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: 0.0.4
 - CLI version: 0.0.4

**Comment by hanshal101** [comment]
Hey @kosmoz this looks like a great issue, Let me get my hands on to this.

**Comment by hanshal101** [comment]
Here I think we should create a Status bar in the package-detail page which should indicate the status of the Pod 
or 
Simply a Status which checks the Pod Readiness

**Comment by kosmoz** [comment]
Hi @hanshal101!

I think what you suggest would be a neat feature that we definitely want to do in the future. 

For this task, I think it would be better to display an alert somewhere on the page that contains the original error message from the `opener`, since it already contains all the info we need, e.g.: 
> could not open argo-cd: could not open entrypoint [anonymous]: no ready pod found for service argocd-server

Here is the documentation for Bootstrap alerts: https://getbootstrap.com/docs/5.3/components/alerts/

To show the alert based on the result of the opener one could probably use [HTMX swap](https://htmx.org/attributes/hx-swap/).

I think in the future it would be even better to have a global "notifications" or "toast" area where we can stream in the alerts via HTMX and websocket but that would definitely be out of scope for this issue.

What do you think? Do you want to give it a go? Or do you have any questions?

**Comment by kosmoz** [comment]
Ok great! Let me know if you have any questions!

**Comment by hanshal101** [comment]
Hey, where do we have to display the error? In the detailed page of a package or the overview page? Because the `open` function runs on the overview page. Also according to me it should be showing an error message in the detailed page.

**Comment by kosmoz** [comment]
> Hey, where do we have to display the error? In the detailed page of a package or the overview page? Because the `open` function runs on the overview page. Also according to me it should be showing an error message in the detailed page.

That's a good question. I think it would make sense to display the error message on the same page where the "open" button was clicked. Since it is possible to click "open" on both the overview and details pages, this means it should be possible to display the error message on both pages. 

One possibility for this would be to add an area in the layout template (`internal/web/templates/layout/base.html`) where HTMX can swap alerts in (also see the `hx-swap` reference I linked above). What do you think?
