### ISSUE TITLE
Update keptn logo

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#374]
[follow-up with keptn logo](https://github.com/keptn/lifecycle-toolkit/pull/3267#discussion_r1524911825)

**Comment by hanshal101** [comment]
Is this issue solved?

**Comment by pmig** [comment]
No, not yet. We need to change the logo probably on the website and in the packages repository.

**Comment by hanshal101** [comment]
Is anyone looking into it or I can pick up?

**Comment by pmig** [comment]
sure, go ahead @hanshal101 ! :-)
