### ISSUE TITLE
Disallow uninstall when there are dependent packages

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#398]
**Is your feature request related to a problem? Please describe.**
We show the uninstall button on the package detail page, even though the operation is not possible because another package depends on it. When clicking uninstall, nothing happens except for the webhook validator error message in the server log.

**Describe the solution you'd like**
The uninstall button should not be visible in such cases. 

In the CLI command we could also abort earlier and state right away that uninstall is not possible. 

**Describe alternatives you've considered**
Showing an error message on the UI if the operation fails. 

**Additional context**

**Comment by hanshal101** [comment]
Hey @christophenne This issue will be active after the Core Functionalities are resolved in #112 ?

**Comment by kosmoz** [comment]
closed in https://github.com/glasskube/glasskube/pull/448
