### ISSUE TITLE
Build numbers not considered in dependency ranges

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#405]
**Describe the bug**
When defining a dependency with a version range which includes a build number, e.g. ">= 1.13.3+2", the build number is ignored and version 1.13.3+1 would also be considered as compatible. 

**To Reproduce**
1. use local package repo, where kubernetes-dashboard depends on cert-manager > 1.13.3+1
2. install cert-manager in version 1.13.3+1
3. install kubernetes-dashboard: cert-manager will not be updated, although it would be required when installing kubernetes-dashboard

**Expected behavior**
Up for discussion: When checking a version against a version constraint, the build number should be considered too. Alternatively, we can also disallow using build numbers in the dependency version ranges, which would make things a lot easier. 

**Glasskube Info (please complete the following information):**
 - Package Operator version: dev
 - CLI version: dev

**Additional context**
Similar to #397

**Comment by pmig** [comment]
@christophenne can this ticket be closed after https://github.com/glasskube/glasskube/pull/426 got merged?

**Comment by christophenne** [comment]
No this is not the same. #426 fixes #397, but afterwards we realized we have the same problem when declaring versions in dependencies. It's up for discussion how we want to deal with it (see expected behavior).

**Comment by christophenne** [comment]
Decision: won't fix but document the constraint
