### ISSUE TITLE
Update to specific package version in CLI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#412]
**Is your feature request related to a problem? Please describe.**
A user can only update an outdated version to the latest version. However when they are on a version newer than latest (e.g. some prerelease of the next major version) they cannot update anymore. Also when dependency requirements make it impossible to update to the latest version from an older version, it might still make sense to update to a version below latest. 

**Describe the solution you'd like**
The `update` command should provide a `-v` version flag like the `install` command. Invalid updates to a smaller version than the one installed must be prohibited.
This version flag is only allowed in combination with updating a single package, as it would make no sense in the "update all" scenario.

Right now there are no plans to offer this on the UI explicitly. 

**Describe alternatives you've considered**

**Additional context**
Related #344 (the missing glue will probably be "calculating" the maximum possible version to update to)

**Comment by hanshal101** [comment]
Hey @christophenne let me look down to this issue.
