### ISSUE TITLE
`glasskube ls` should not show latest available version if installed version is newer than latest

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#441]
**Is your feature request related to a problem? Please describe.**
Output of `glasskube ls` when having installed keptn in a later version than latest:
```
 go run cmd/glasskube/main.go ls
NAME                  STATUS         VERSION                              AUTO-UPDATE
argo-cd               Not installed                                         
cert-manager          Ready          v1.14.2+1                              
cyclops               Not installed                                         
ingress-nginx         Not installed                                         
keptn                 Ready          v2.0.0-rc.1+1 (v0.10.0+1 available)    
kubernetes-dashboard  Not installed                                         
```

**Describe the solution you'd like**
In the above scenario, "(v0.10.0+1 available)" should not be shown because the version marked as latest is older than the version installed. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hanshal101** [comment]
Hey @christophenne can I take this issue?

**Comment by jakepage91** [comment]
Hey there @hanshal101 as recently mentioned in the updated [contributor guidelines](https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md#-contributing-best-practices), we would really appreciate issues being done one at a time. I see you are assigned on at least one other issue, how is that one coming along?

**Comment by hanshal101** [comment]
Well this looks good for me:
```
PS H:\glasskube> .\main.exe ls
NAME                  STATUS         VERSION                                  AUTO-UPDATE
argo-cd               Ready          v2.10.5+1 (v2.10.4+1 available)
cert-manager          Ready          v1.14.2+1                                Enabled  
cyclops               Not installed
ingress-nginx         Not installed
keptn                 Ready          v2.0.0-rc.1+1 (v2.0.0-rc.2+1 available)
kubernetes-dashboard  Not installed
```

**Comment by christophenne** [comment]
Please have a look at our discussion yesterday, where I tried to explain this: https://github.com/glasskube/glasskube/pull/461#discussion_r1551978737 

If the version marked as latest, is older than the version installed, we do not want to show the text "(v2.10.4+1 available)".

**Comment by christophenne** [comment]
@hanshal101 do you want to work on it?

**Comment by hanshal101** [comment]
Yup
