### ISSUE TITLE
Show a different button state if a package is currently being uninstalled

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#456]
Currently, a package is displayed as "pending" after starting an uninstall action, provided that the package-operator is running in the cluster. If no package-operator is running, the displayed state doesn't change until the package is finally removed after GC has completed (we use foreground deletion for Glasskube packages).

It would be better to detect if a package has been marked for deletion and display a different button state on the overview and details pages if it is. To start with, the button could look like the "pending" button but with a different text, e.g. "uninstalling". It is important that the button is also `disabled`.

A resource can be considered marked for deletion if it has a `DeletionTimestamp`:
```go
if !pkg.DeletionTimestamp.IsZero() {
  // pkg is being deleted ...
}
```

**Comment by Baalekshan** [comment]
@kosmoz Can this be worked on now ?

**Comment by kosmoz** [comment]
Sure, go ahead!
