### ISSUE TITLE
CLI version completion when updating to specific version

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#462]
**Is your feature request related to a problem? Please describe.**
Once #412 is done, the `glasskube update` command is able to update a package to a specific version. However, it does not yet support shell completion yet like the install command does. 

**Describe the solution you'd like**
When the user enters `glasskube update <package-name> -v` and then presses the tab key, a list of possible versions should appear, from which the user can choose. This is similar to what the install command already does when the `-v` flag is given, however its not exactly the same: the update command completion should only show those versions of the package, which are newer then the currently installed version. 

**Describe alternatives you've considered**

**Additional context**
Follow up of #412

As an entrypoint, you can take a look at the `install` command, specifically the function `completeAvailablePackageVersions`. It will have to be adapted to only show versions that are newer than the currently installed one (meaning that the package also needs to be fetched first).

To be fair, its a trickier "good first issue". As always, you can contact us any time in case of questions or problems.

**Comment by hanshal101** [comment]
Do we need something like this:
```
$ glasskube update keptn -v
>v1.01
>v2.0.1
>v3.0.1
>v4.0.1
```
And from here user can select the version and update it.
This might also work for the install command.

**Comment by hanshal101** [comment]
Hey @christophenne are we still working on this issue?

**Comment by christophenne** [comment]
> Do we need something like this:
> 
> ```
> $ glasskube update keptn -v
>  > v1.01
>  > v2.0.1
>  > v3.0.1
>  > v4.0.1
> ```
> 
> And from here user can select the version and update it. 

Yes, that's the requirement. 

> This might also work for the install command.

As I tried to describe – this already works for the install command, and whoever implements it, should take a look there and implement it similarly.

**Comment by hanshal101** [comment]
Well here do we have to show only those `versions` that can be updated to. Or all versions.

**Comment by christophenne** [comment]
From the description: 

> the update command completion should only show those versions of the package, which are newer then the currently installed version.

Let's do it like this.

**Comment by hanshal101** [comment]
Can you help me with testing the code in my local machine. Well I tried building the CLI `main.exe`. But this didnt work for me
