### ISSUE TITLE
Handle `v` prefix in versions in install and update command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#463]
**Is your feature request related to a problem? Please describe.**
`install` and `update` commands offer the possibility to update to a specific verison with the `-v` flag. The version entered must have the `v` prefix, or otherwise the package will not be found in the package repo. That's not the greatest user experience.

Example:
`glasskube install keptn -v v2.0.0-rc.1+1` works, because the version number has the `v` prefix.
`glasskube install keptn -v 2.0.0-rc.1+1` does not work, because the version number is missing the `v`.

**Describe the solution you'd like**
The user should be able to enter their version without the `v` prefix. This should work for the install command and also for the update command. 

**Describe alternatives you've considered**

**Additional context**
#412 is still in progress.

**Comment by Aryakoste** [comment]
Hello @christophenne. I would like to work on this issue.

**Comment by sumeshmurali** [comment]
@christophenne this isssue is still unassigned, right? Can I start working on this?

**Comment by pmig** [comment]
@sumeshmurali sure - If you encounter any questions feel free to contact us on Discord

**Comment by hanshal101** [comment]
Hey @sumeshmurali are you still working on this? If not I'm up for this issue.

**Comment by sumeshmurali** [comment]
> Hey @sumeshmurali are you still working on this? If not I'm up for this issue.

I opened the PR now.
