### ISSUE TITLE
Too "GUIsh" install, need --yes option

### ISSUE THREAD

**Issue by aleksey-hariton** [glasskube/glasskube#468]
Looks like there is no way to make package install from script.
I cant install package without keyboard console interaction, there is no `--yes` option like in `apt/yum`.
Maximum what I achieved 

```
yes | glasskube install argo-cd --enable-auto-updates
```

but thats ugly and will not work on Windows...

**Comment by kosmoz** [comment]
I think this is a great idea!

**Comment by sumeshmurali** [comment]
Can I start working on this issue?  I guess, I'll need to add a `--yes` flag [here](https://github.com/glasskube/glasskube/blob/main/cmd/glasskube/cmd/install.go#L179) and if its true ignore the `YesorNoPrompt`.

I assume, update and uninstall would require an `--yes` option too.

**Comment by kosmoz** [comment]
Sure, go ahead!

Uninstall already has a `--force` flag that does the same. Let's keep it this way for now. 

Let us know if you have any more questions!

**Comment by sumeshmurali** [comment]
I have opened a PR for this. Let me know if any changes are required.
