### ISSUE TITLE
kubernetes-dashboard update from 2.7.0+1 to 2.7.0+2 is broken

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#478]
**Describe the bug**
When having 2.7.0+1 installed, and updating to 2.7.0+2 (changing from manifest to helm chart), the package kubernetes-dashboard has status "InstallationFailed" and stays there. Error message: 

"An error occurred during the update: package update for kubernetes-dashboard failed: Package is not ready (reason InstallationFailed): flux: Helm install failed for release kubernetes-dashboard/kubernetes-dashboard with chart kubernetes-dashboard@6.0.8: Unable to continue with install: ServiceAccount "kubernetes-dashboard" in namespace "kubernetes-dashboard" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubernetes-dashboard"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kubernetes-dashboard""

**To Reproduce**
1. Install kubernetes-dashboard in 2.7.0+1
2. When installation succeeded, update to 2.7.0+2

**Expected behavior**
Update should work.

**Screenshots**
![Screenshot from 2024-04-05 13-34-49](https://github.com/glasskube/glasskube/assets/7556574/e7ee453e-e196-4338-ab0a-4090a0bcb54b)

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: 1.28
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: dev
 - CLI version: dev
 
**Additional context**

**Comment by kosmoz** [comment]
We will discuss this again if we touch on implementing another helm adapter or package adoption.
