### ISSUE TITLE
Move the search bar in the package section of the website

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#481]
**Is your feature request related to a problem? Please describe.**
As can be seen in the screenshot the filter search bar in the [website's package section](https://glasskube.dev/packages/) is in a peculiar spot. A better place would be on the opposite side beside the `Filters` title for example. We are open to different options for the positioning of the search bar as long as it is intuitive and improves the sites usability. 

<img width="1381" alt="Screenshot 2024-04-05 at 16 53 47" src="https://github.com/glasskube/glasskube/assets/38757612/5fa183b8-e4c9-46b8-957a-33642c71bdda">

**Describe the solution you'd like**
A functioning filters search bar in a more user friendly position

**Comment by Aryakoste** [comment]
Hello @jakepage91 @kosmoz. I would like to work on this issue.
