### ISSUE TITLE
Handle bootstrap errors gracefully when glasskube is not connected to the internet

### ISSUE THREAD

**Issue by Baalekshan** [glasskube/glasskube#491]
**Is your feature request related to a problem? Please describe.**

When the user is not connected to the internet and `glasskube bootstrap` is used the bootstrap fails and returns a memory invalid or nil pointer deference error but instead we should print a message as glasskube is not connected to the internet. Something like this

```
~$ glasskube bootstrap
⚠️ Glasskube is not connected to the internet, cannot bootstrap.
```

**Describe the solution you'd like**
Improve error handling for `cmd/bootstrap.go`

Addition from @christophenne: I think the error message doesn't necessarily have to be "not connected to internet", but can be more generic. The point where the first call to some http endpoint is made, is when fetching the lastest version of glasskube. It should be fine to do the same error handling as used in `clientutils.FetchResources`.

**Describe alternatives you've considered**

**Additional context**

**Comment by Baalekshan** [comment]
@christophenne this could be a good-first-issue

**Comment by christophenne** [comment]
@Baalekshan good point, but I think this is being solved already with #524, right?

**Comment by Baalekshan** [comment]
No that's a different issue involving --url flag.
This one is for showing that glasskube is not connected to the internet when tried bootstrapping.This one might be status code 503 service unavailable when device is offline. #524 deals with 404 error.

**Comment by christophenne** [comment]
@Baalekshan fair enough, good input.

**Comment by Aryakoste** [comment]
Hello @christophenne. I would like to work on this issue.
