### ISSUE TITLE
ArgoCD Guide

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#497]
**Is your feature request related to a problem? Please describe.**
Create an ArgoCD guide 

**Additional context**
Ref #307

**Comment by Adithyanstyle1** [comment]
The issue is closed or still live?

**Comment by pmig** [comment]
Hi @Adithyanstyle1 I am still working on it

**Comment by pmig** [comment]
resolved in https://github.com/glasskube/gitops-template/
