### ISSUE TITLE
Changing the local port for `glasskube open`

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#523]
**Is your feature request related to a problem? Please describe.**
There might be issues if the local port is already in use when using the `open` command. It should be possible to change the default if desired.

**Describe the solution you'd like**
On the CLI, a different port can be specified with `--port`. If the flag is used and there are multiple entrypoints for the package and no single entrypoint is specified via CLI argument, the command should exit with an error. If the flag is not specified, the default from the manifest should be used.

**Describe alternatives you've considered**
Adding logic to pick a different random port (similar to what we already to for the `serve` command), but I think this would be more complicated an error prone in this situation, since the listener can not be reused. We might have to extract the port from the listener, then close it and reuse the same port for another listener… OTOH there is no reason why both features shouldn't exist.

**Additional context**
No idea how to do this on the UI :thinking:

**Comment by hanshal101** [comment]
Can I take this issue?

**Comment by hanshal101** [comment]
Hey @kosmoz here should I make a different function in the `glasskube\pkg\open\open.go` like a function if `spec_port` is mentioned.
Eg:
```
func (o *opener) SpecPortOpen(ctx context.Context, packageName string, entrypointName string, port string) (*OpenResult, error) {}
```

**Comment by kosmoz** [comment]
I think it would be fine to add the port argument to the existing Open function
