### ISSUE TITLE
`glasskube version` should not show an error when not bootstrapped

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#529]
**Is your feature request related to a problem? Please describe.**
`glasskube version` shows an error when not bootstrapped yet, but it's a valid case to not have it bootstrapped yet and check the client version.

**Describe the solution you'd like**
Instead of the error it should show an information that it's not bootstrapped yet, and a hint that it can be done with the `bootstrap` command. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Aryakoste** [comment]
Hello @christophenne. I would like to work on this issue.
