### ISSUE TITLE
Error updating using `bootstrap`

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#613]
**Describe the bug**
When using `glasskube bootstrap` to upgrade the cluster components from version 0.2 to 0.3 there is an error because the webhook cert job cannot be updated.

**To Reproduce**
1. Setup a fresh cluster
2. Bootstrap an older version
3. Bootstrap a newer version

**Expected behavior**
If a job with the same name already exists, do one of the following:
- It is not updated
- It is deleted and re-created using the updated manifest

This should not be limited to the webhook cert job, it should work for any potential job we might add.

**Additional context**

**Comment by hanshal101** [comment]
Hey @kosmoz is this issue for the community?

**Comment by hanshal101** [comment]
Yup, I can try this.

**Comment by kosmoz** [comment]
Alright, let us know if there are any questions!

**Comment by hanshal101** [comment]
Okay, here I what we are trying to solve is:

## ERROR

- When we update the operator version from `0.2.0` -> `0.3.0` , an error occurs something like this:
![image](https://github.com/glasskube/glasskube/assets/122217807/d71015f2-b654-48a8-9898-d6eaf17cfb9c)

- This error which says the conflict in the `name` of the `glasskube-webhook-cert-init` job. 

## SOLUTION

- Well here we can add a checkpoint in the CLI if any desired

**Comment by hanshal101** [comment]
Okay, here I what we are trying to solve is:

## ERROR

- When we update the operator version from `0.2.0` -> `0.3.0` , an error occurs something like this:
![image](https://github.com/glasskube/glasskube/assets/122217807/d71015f2-b654-48a8-9898-d6eaf17cfb9c)

- This error which says the conflict in the `name` of the `glasskube-webhook-cert-init` job. 

## SOLUTION

- Well here we can add a checkpoint in the CLI if any desired job-name matches with the existing job-name. First we need to delete the existing job and then install the desired one.

**Comment by kosmoz** [comment]
Yes this is exactly the error we are talking about here. 

I think the solution of not updating the job would be preferable for now. Something like this (in `applyManifests`; pseudo code):
```go
for obj := range objs {
  if obj.GetKind() == "Job" {
    if /* Check if resource exists */ {
      continue;
    }
  }
  /* Not a job, or doesn't exist -> continue as usual */
}
```

Let me know if this is enough for you to get started

**Comment by hanshal101** [comment]
Yup, I thought of this but was unsure, what if we try this in `preprocessManifests`
