### ISSUE TITLE
Quickwit package integration

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#626]
**Package Information**
 - Name: Quickwit
 - Source Code: https://github.com/quickwit-oss
 - Helm Chart: https://github.com/quickwit-oss/helm-charts
 - Website: https://quickwit.io/

**If you are an author of this project, let us know**
I am not the author of the package, but we already had a call with @fmassot about the package integration and will support him with an initial version.

**Additional information:**
Quickwit requires an s3 bucket and a postgres database for storage.

For the postgres can create a dependency on the cnpg-operator and but a manifest in the Glasskube package and than reference the access credentials from the cnpg secret.

For the S3 bucket we need to find a solution.

**More information:**
 - https://quickwit.io/docs/deployment/kubernetes/helm

**Comment by fmassot** [comment]
Thanks @pmig for opening the issue.

To give you a bit more context about PostgreSQL dependency, we use it for storing metastore data, and it's very lightweight. It's possible to remove the PostgreSQL and use S3 to store the metastore data. If this could simplify the first iteration, I think the S3 metastore is a good option.
