### ISSUE TITLE
JSON/YAML output for CLI commands

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#629]
All CLI commands should support specifying an output format if applicable. This can be done using the `--output` flag (short: `-o`). This flag is optional (default: empty) and can be set to "json" or "yaml". Output should be written to STDOUT.

If a command modifies some resources, the output should be of the resource after modification. 
Those commands should also provide a `--dry-run` option. 

### Examples
```
# list packages as yaml
glasskube ls -o yaml
# simulate install and write json output to a file
glasskube install foo-pkg --dry-run --output=json > foo.json
```

### Subtasks
- [x] https://github.com/glasskube/glasskube/issues/465
- [x] #655 
- [x] #656
- [x] #659
- [x] #657
- [x] #660
- [x] #658
- [x] #661
- [x] #724
- [x] #725

**Comment by Aryakoste** [comment]
Hello @kosmoz I would like to work on this issue.

**Comment by jakepage91** [comment]
All yours!

**Comment by christophenne** [comment]
Hi @Aryakoste, we created some subtasks now, since these are a lot of separate tasks. Could you please pick one of the linked issues, then we'll re-assign you to that, thanks!

**Comment by Aryakoste** [comment]
@christophenne can I work on multiple tasks.

**Comment by christophenne** [comment]
@Aryakoste which one would you like to do?

**Comment by Aryakoste** [comment]
I can work on update and configure commands tasks. @christophenne

**Comment by christophenne** [comment]
I think you can start with #657 and #658 – usually we try to have contributors work at only one issue at a time, but in this case it makes a bit more sense because the tasks are similar.

Can you please shortly comment in these two? I think you need to be "active" in the issue, otherwise github does not allow me to assign you it seems.

**Comment by Aryakoste** [comment]
I have commented in the above 2 issues.

**Comment by christophenne** [comment]
All done :tada:
