### ISSUE TITLE
Auto-Update label should be an annotation

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#634]
**Is your feature request related to a problem? Please describe.**
We use the `packages.glasskube.dev/auto-update` label to decide whether a package should be updated automatically or not. However, labels are used to attach identifying information to a custom resource, see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/. Non-identifying information should be attached by using annotations: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ 

**Describe the solution you'd like**
Wherever the auto-update label is being used in the code base, it should be changed to use an annotation instead. 

**Additional context**
This came up here: https://github.com/glasskube/glasskube/pull/618#discussion_r1598377945

**Comment by UtkarshUmre** [comment]
I would like to work on this issue
