### ISSUE TITLE
Show uninstalling state in `list` and `describe` command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#654]
**Is your feature request related to a problem? Please describe.**
As a follow up of #456 we should also show "uninstalling" in the CLI, i.e. `list` and `describe` commands, in order to keep CLI and UI consistent. 

**Describe the solution you'd like**
As defined in #456, when a package is in the progress of being uninstalled, its status should be "Uninstalling" instead of "Pending". 

**Describe alternatives you've considered**

**Additional context**
#456

**Comment by bishalbera** [comment]
@christophenne Hello, can I work on this issue?

**Comment by christophenne** [comment]
@bishalbera sure, go for it and don't hesitate to ask questions here or in discord!

**Comment by bishalbera** [comment]
Hey @christophenne, I've made the required changes and now it's showing the status as uninstalling when a package is being uninstalled using the `list` and `describe` command(below I've attached the pic). Also I've tested it as instructed in the contributing guideline. I've noticed that whenever a package is installing its status is showing pending in the CLI. I think we can change it to show `installing` by checking whether the CreationTimestamp is zero or not. Should I also implement it?

<img width="887" alt="Screenshot 2024-05-23 at 3 31 10 PM" src="https://github.com/glasskube/glasskube/assets/123734227/855550df-7238-45ab-bee7-1acb3c8cb975">
<img width="887" alt="Screenshot 2024-05-23 at 3 32 21 PM" src="https://github.com/glasskube/glasskube/assets/123734227/21f24a71-54e7-4f16-a721-b3c7f4da52fe">
<img width="887" alt="Screenshot 2024-05-23 at 3 33 37 PM" src="https://github.com/glasskube/glasskube/assets/123734227/214305ba-5f71-4cae-86c2-81a230c3f366">

**Comment by christophenne** [comment]
Thanks, will check it out today. As for the "Installing" label, it's a good idea but I would stick with "Pending", because it's also shown whenever the package is being reconciled, which doesn't always have to be an installation (for example after changing a configuration value), and Pending would be a more general term for that. So I think this should be fine.

**Comment by bishalbera** [comment]
Ok I understood your point.I have submitted the pull request. Please check it whenever you have time. Also, I noticed that the PR template is not working in the `contributing.md` file. I encountered this issue while creating the pull request. @christophenne
