### ISSUE TITLE
Add `--dry-run` support for `glasskube configure`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#661]
See #629 for details.

The `--dry-run` flag can be used by users, who want to simulate configuring a package, but don't actually want to configure it.

**Comment by doncicuto** [comment]
Hi @christophenne, may I take this one. The help-wanted label is not set but I guess it should be similar to https://github.com/glasskube/glasskube/pull/727 Thanks!

**Comment by christophenne** [comment]
Hi @doncicuto, thanks for your interest, but we're currently refactoring a lot of the commands for the namespaced packages feature, so I think it would make sense to wait with this one for a while.

**Comment by doncicuto** [comment]
I understand @christophenne, thanks!

**Comment by christophenne** [comment]
Hi @doncicuto, are you still interested in this?

**Comment by doncicuto** [comment]
Sure!, let me work on it :smile:

**Comment by christophenne** [comment]
Cool, thanks!

**Comment by doncicuto** [comment]
Hi @christophenne the code is ready but I've some doubts before I create the PR:

1. There are already many dry-run enabled commands, but the flag shows different messages ("Do not make any changes but run all validations", "simulate the installation of package without actually installing it"...). Could the dry-run flag has the same flag description for all commands like "execute command in dry run mode" like Docker does?  This way we could have a dry_run_options.go file where the definition could be reused:

```
package cmd

import (
	"github.com/spf13/cobra"
)

type DryRunOptions struct {
	DryRun bool
}

func (opt *DryRunOptions) AddFlagsToCommand(cmd *cobra.Command) {
	cmd.Flags().BoolVar(&opt.DryRun, "dry-run", false, "simulate the execution of the command without making any changes")
}
```
If you are fine with that I'd update the existing commands flag accordingly

2. How could I test the configure command. I'm having problems to specify values that can be updated as I don't know which values are applied to a package (it seems I can't create new values e.g --value="name=test,test"). Also I'd like to check that the dry run option is not indeed changing values, so my question may be dumb but how can I get the configured values for a package so I can test the command before and after.

3. I've seen that the flags descriptions for different commands mixes lowercase or uppercase description (for example the same command has `output format` and `Skip confirmation prompt`). I think they should be all lowercase or uppercase but not both (kubectl, docker uses uppercase), I know it's a silly improvement but would you mind if I open an issue for this?

Thanks

**Comment by christophenne** [comment]
@doncicuto thanks for your suggestions.
1. Reusing the same option and same message sounds reasonable to me. @kosmoz what do you think?
2. Do have minikube and the operator running on your system? It's described here: https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md#package-operator – when the operator is running, you can install a package with configuration values (e.g. `k8sgpt-operator`) – it doesn't matter if installation fails, you should still be able to change the configuration with the configure command and therefore test your implementation. You can show the current configuration with either `glasskube describe`, or on the UI package detail page of the package. 
3. Thanks for noticing, you can definitely open an issue for such things :)

**Comment by doncicuto** [comment]
Thanks @christophenne for your answers, I'll create the issue for point 3. For the second point, indeed I've the operator and installed some packages. If I try to describe the sealed-secrets package I see no values there:

```
Package: sealed-secrets — A Kubernetes controller and tool for one-way encrypted Secrets
Version:     v2.15.3+1
Status:      Ready
Auto-Update: Enabled

Package repositories:
 * glasskube (installed)

References: 
 * Glasskube Package Manifest: https://packages.dl.glasskube.dev/packages/sealed-secrets/v2.15.3+1/package.yaml
 * ArtifactHub: https://artifacthub.io/packages/helm/bitnami/sealed-secrets

Long Description:
To use this package, install the kubeseal (https://github.com/bitnami-labs/sealed-secrets#kubeseal) application. Use kubeseal with the --controller-namespace=sealed-secrets-system flag. For more information, check out the official documentation (https://github.com/bitnami-labs/sealed-secrets#usage).
```
would you provide me an example on adding a value using the configure command for this package. Sorry, I don't usually ask these kind of questions :flushed:

**Comment by christophenne** [comment]
No worries @doncicuto, please try another package, like `k8sgpt-operator` or `kube-prometheus-stack`, because `sealed-secrets` for example simply has no configuration values, so there is nothing to show or configure :)

**Comment by kosmoz** [comment]
> 1. Reusing the same option and same message sounds reasonable to me. @kosmoz what do you think?

Yeah, sounds like a good idea

**Comment by doncicuto** [comment]
Thanks @christophenne using kube-prometheus-stack will help me to test the dry-run, now I know a little more about Glasskube
