### ISSUE TITLE
Support repo deletion with `glasskube repo delete [repoName]`

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#681]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to delete a `PackageRepository` custom resource via our CLI, one would have to delete the resource manually instead.

**Describe the solution you'd like**
There should be a `repo`-subcommand `delete`, which can be used like this:

`glasskube repo delete [repositoryName]`

The command should verify whether no packages are currently installed from this repository. If there are packages installed from the repo, the deletion should be aborted with this error message: "Repository [repoName] cannot be deleted, because the following packages are installed from this repository: [list of package names]". 

Before deleting, the user should be asked to confirm deleting the repository, by using the existing Yes/No prompt, where `No` should be the default. The prompt should be: "[repoName] will be removed from your current cluster ([current-context]). Continue? (y/N)"

**Describe alternatives you've considered**

**Additional context**
Ref #195

**Comment by Baalekshan** [comment]
@christophenne I like to work on this.

**Comment by christophenne** [comment]
Great, thanks!

**Comment by christophenne** [comment]
Hi @Baalekshan, just wanted to check in here and ask how it's going with this issue? If there are any open questions, please feel free to ask :)

**Comment by Baalekshan** [comment]
@christophenne I didn't had the time to solve the issue for the past days. Only going to take a look now. Surely, I ask if I have any questions.
