### ISSUE TITLE
Add `--no-progress` cli flag

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#709]
**Is your feature request related to a problem? Please describe.**
As we introduced autoated tests in our ci enviornment (e.g. https://github.com/glasskube/packages/actions/runs/9266452356/job/25492645517) our progress spinners are quite noise (printing 10 lines every second)

**Describe the solution you'd like**
Globally introduce a `--no-progress` cli flag that prevents progress logging to the cli.

**Additional context**
This will also be used in our automated testing infrastrucutre.

**Comment by denilbhatt0814** [comment]
hello @pmig, I would love to take this up

**Comment by pmig** [comment]
@denilbhatt0814 sure go ahaead
