### ISSUE TITLE
Add `purge` command to remove Glasskube from a cluster

### ISSUE THREAD

**Issue by RaceFPV** [glasskube/glasskube#715]
**Is your feature request related to a problem? Please describe.**
At the moment there is no guide/instruction/way to remove glasskube from a cluster

**Describe the solution you'd like**
glasskube bootstrap uninstall or similar

**Describe alternatives you've considered**
Worst case a list of manifests etc to uninstall in a readme etc

**Comment by pmig** [comment]
Hi @RaceFPV,

Thank you for your feature request. This indeed is not yet documented / implemented. As quick fix you could run following commands:

```bash
kubectl delete ns glasskube-system
kubectl delete crd packages.packages.glasskube.dev packageinfos.packages.glasskube.dev packagerepositories.packages.glasskube.dev
```

@kosmoz @christophenne  we could also add labels to our crds so we could implement a `glasskube purge` command that deletes all crds with our custom `glasskube-system-resource` label?

**Comment by kosmoz** [comment]
Another way to quickly remove all traces would be this:
```
kubectl delete -f https://github.com/glasskube/glasskube/releases/download/[insert-installed-version-here]/manifest-aio.yaml
```
But I agree that we should at least document this. 

something like a purge command should be easy to implement, since we already know anyways what we install during bootstrap.

I don't think this feature would be needed in the UI though.

**Comment by kosmoz** [comment]
A possible procedure for this `purge` command would be:
1. Determine the installed version (we can already do this)
2. Download the manifest for that version (we can already do this as well)
3. Delete all resources contained in this manifest using a dynamic client (i.e. roughly the reverse of what bootstrap does)

Before deleting anything, it should ask the user for confirmation and the prompt should include the name of the current context. The `purge` command should also include a `--yes` flag that skips this confirmation step.

**Comment by RaceFPV** [comment]
I ended up running the kubectl delete -f <manifest url.yaml> as deleting the namespace and crd's missed a lot of lingering components. The one thing I did notice though is that deleting via the manifest also deleted the flux namespace completely, which is fine for me as I use argo instead of flux however if anyone else does use flux they could lose their flux deployment/setup in the removal process.

**Comment by kosmoz** [comment]
That's a good point, we should keep it in mind for the implementation. Thanks for taking the time to point it out!

**Comment by Aryakoste** [comment]
Hello @kosmoz I would like to work on this issue.

**Comment by kosmoz** [comment]
Hi @Aryakoste, thank you for your enthusiasm for contributing to our project! Since there are currently [three](https://github.com/glasskube/glasskube/issues?q=assignee%3AAryakoste+is%3Aopen) open issues assigned to your name already, I would prefer to prioritize your existing PRs:
- https://github.com/glasskube/glasskube/pull/669
- https://github.com/glasskube/glasskube/pull/727

Please don't hesitate to let us know if you have any questions regarding a review comment, or need assistence in another way.

**Comment by Aryakoste** [comment]
@kosmoz Both PRs completed.
