### ISSUE TITLE
Implement specific (multi repository) package upgrades / downgrades

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#716]
**Is your feature request related to a problem? Please describe.**
As user I want to change the version of an installed package (and even install the package from a different repository)

**Describe the solution you'd like**
Introduce a new repository dropdown for not yet installed and already installed packages and add a version select to already installed packages, which changes the package version.
I also want to be able to change the auto upgrade checkbox for already installed packages.

**Describe alternatives you've considered**
It is already possible to install / configure specific versions from the cli (`glasskube install keptn --version=v2.0.0-rc.1+1`)

**Additional context**
I already created a mockup of the app detail page:

![Glasskube package version and repo switch](https://uploads.linear.app/df577539-a424-4cdd-a9e7-429a979eefe9/909db2df-a19b-47a7-929f-5b9b31d7fd74/5ebc4cc9-514b-4793-bb9b-6ff0bcd5e914?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2RmNTc3NTM5LWE0MjQtNGNkZC1hOWU3LTQyOWE5NzllZWZlOS85MDlkYjJkZi1hMTliLTQ3YTctOTI5Zi01YjliMzFkN2ZkNzQvNWViYzRjYzktNTE0Yi00NzkzLWJiOWItNmZmMGJjZDVlOTE0IiwiaWF0IjoxNzE3MTQ4MjgxLCJleHAiOjMzMjg3NzA4MjgxfQ.AbfeL2tRVRgRJUPATJ4T_nmHrf9Lcf8uvmZy8SqpHGg)

**Comment by christophenne** [comment]
* As discussed, switching repository and version back and forth without restrictions is more of a feature for package maintainers and testers, than a feature for actual package management users. Therefore we will introduce a "maintainer mode" (default off), which can be enabled in the settings with a warning about potential consequences (the cluster could go into a broken state). 
* Enabling/disabling auto-update after installation is a feature on its own: #718
