### ISSUE TITLE
Enable/disable auto-updates for installed packages in UI

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#718]
**Is your feature request related to a problem? Please describe.**
Auto-updates can only be enabled/disabled at the time of installation, but not afterwards. 

**Describe the solution you'd like**
On the package detail page, there should be a switch to turn on/off auto-updates. 

**Describe alternatives you've considered**

**Additional context**
Follow-Up of #716

**Comment by Utkarsh067** [comment]
Hello @christophenne, I am new here. Can you please guide how I can contribute in the GlassKube OpenSource.
It will be really helpful.

**Comment by pmig** [comment]
HI @Utkarsh067 please check out our [contributing guidelines](https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md)

**Comment by babautkarsh** [comment]
hi @pmig  is the feature addition of managing repository at the time of installation is done or closed

**Comment by pmig** [comment]
this feature is not related to managing repositories, but actually a duplicate issue of: https://github.com/glasskube/glasskube/issues/1091 - so closing this now
