### ISSUE TITLE
Add confirmation to `bootstrap` command

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#719]
**Is your feature request related to a problem? Please describe.**
The bootstrap command starts it's work right away, which can be dangerous if a user has the wrong kubeconfig context selected.

**Describe the solution you'd like**
Before doing anything, `bootstrap` should ask the user for confirmation, the prompt should include the current context name. For example:

    Glasskube will be installed in context [name-of-current-context].
    Continue? (Y/n)

There should also be a `--yes` flag, that skips this step.

If the bootstrap process is triggered via the UI, the confirmation prompt MUST NOT be shown!

**Comment by bishalbera** [comment]
@kosmoz Can I work on this?
