### ISSUE TITLE
Indicate default repository via UI

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#733]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to determine via the ui, if a repository is configured as default repository:

![image](https://github.com/glasskube/glasskube/assets/3041752/151388de-c4b4-4b42-ba7d-8aa22061780c)

**Describe the solution you'd like**
Add an indication to the UI that a repository is configured as default repository.

**Describe alternatives you've considered**
Currently it is necessary to describe the custom resource.

**Additional context**
Whether a given `PackageRepository` is marked as the default repository can be determined by checking  [`IsDefaultRepository()`](https://pkg.go.dev/github.com/glasskube/glasskube/api/v1alpha1#PackageRepository.IsDefaultRepository).

**Comment by krishnpalchouhan** [comment]
Hey I can looking into this

**Comment by krishnpalchouhan** [comment]
Please remove my name from this task as my tech stack does not match the requirements. I'm looking for opportunities to contribute in a TypeScript or JavaScript space and will try to find something more suitable to work on.

Thank you.

**Comment by aminsaedi** [comment]
Hi, I would like to work on this issue. Is it still available?
