### ISSUE TITLE
`--repository` flag for `glasskube list` command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#750]
**Is your feature request related to a problem? Please describe.**
`glasskube ls` always shows the packages of all configured repositories, but there should be a way to look at packages of one specific repository.

**Describe the solution you'd like**
`glasskube ls` should have a flag `--repository`, which can be used this way: `glasskube ls --repository [repoName]`. Only the packages defined in the given repo will then be listed. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ayushtessell** [comment]
Can I work on this issue please.

**Comment by chetak123** [comment]
Can I work on this issue please.

**Comment by christophenne** [comment]
> Can I work on this issue please.

Sure, don't hesitate to ask if you have any questions.

**Comment by STAR-173** [comment]
Hey @christophenne,
Just wanted to know if this issue is still open for development? Would love to contribute to this repo.

**Comment by rushatgabhane** [comment]
hey same! i'd love to help on this issue

**Comment by christophenne** [comment]
hi @chetak123, how's it going with this task? is there anything we can help you with?

hi @STAR-173 @rushatgabhane, thank you, we will open a few new issues soon that you can work on – but this one is already taken.

**Comment by kosmoz** [comment]
Hey @chetak123, I unassigned you because of prolonged inactivity. If you are still interested in contributing, please check out our open issues.

**Comment by Srikrishnabh** [comment]
@kosmoz can you please assign to me

**Comment by kosmoz** [comment]
> @kosmoz can you please assign to me

Sure, let us know if you need anything!

**Comment by kosmoz** [comment]
Hey @Srikrishnabh, are you still working on this issue? Do you have any questions?

**Comment by Srikrishnabh** [comment]
hey @kosmoz yes, I'm working on it. My approach is to pass repo argument to below func
https://github.com/glasskube/glasskube/blob/main/pkg/list/lister.go#L137
```
func (l *lister) fetchRepoAndInstalled(ctx context.Context, options ListOptions, typeOpts typeOptions) (
```

and filter the repos in the below code loop.
```
	for i, indexPackage := range index.Packages {
		...
       }
```
https://github.com/glasskube/glasskube/blob/main/pkg/list/lister.go#L202

If this approach is fine, I will implement.

**Comment by kosmoz** [comment]
That sounds reasonable. It probably makes sense to pass it as part of the ListOptions struct

**Comment by Srikrishnabh** [comment]
Thanks, Sure will make the change and raise PR.
