### ISSUE TITLE
Show repository status on settings page

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#751]
**Is your feature request related to a problem? Please describe.**
On the UI, the settings page shows a green or red circle next to each repository, indicating whether it has status "Ready" or not. 

**Describe the solution you'd like**
There should be an additional text when hovering with the mouse over this circle. The html `title` attribute should be used. The two possible texts are "Ready" and "Not Ready".

**Describe alternatives you've considered**

**Additional context**

**Comment by WaterLemons2k** [comment]
Hi @christophenne, I would like to work on this issue, can you assign it to me?
