### ISSUE TITLE
`--skip-open` flag for `glasskube serve` command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#753]
**Is your feature request related to a problem? Please describe.**
The `glasskube serve` command always opens a new browser tab. In cases where the command is often stopped and restarted (like development), this can be annoying. 

**Describe the solution you'd like**
The command should have a flag `--skip-open` (shorthand: `-s`). When it is set, the page should not be opened in the browser. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mahiro72** [comment]
Hello @christophenne , I'm interested in working on this issue. Would it be okay for me to pick it up?

**Comment by pmig** [comment]
@mahiro72 yes, sure
