### ISSUE TITLE
Suppress 404 error for packages without a giscus discussion

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#755]
**Is your feature request related to a problem? Please describe.**
On the UI, when opening the package detail page of a package, which does not have a corresponding discussion (https://github.com/glasskube/glasskube/discussions/categories/packages) yet, an error will be logged to the console: "failed to get discussion counts from giscus: wrong status code: 404 Not Found". 

However, this is a legit case and should not be logged, as this could confuse the user. 

**Describe the solution you'd like**
The giscus API is called here: `internal/web/discussions.go:discussionBadge` – this is the endpoint to load the number of reactions on the package detail page. When calling `giscus.Client().GetCountsFor(pkgName)`, the returned error should be checked whether it is a NOT_FOUND error (404) or not. If it is, then the error should not be logged.

**Describe alternatives you've considered**

**Additional context**

**Comment by doncicuto** [comment]
Hi @christophenne, I'd like to work on this issue if possible and you can assign it to me, thanks in advance
