### ISSUE TITLE
Change flag name of `--force` to `--yes` for  `glasskube uninstall`

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#760]
The `uninstall` command was the first one to have such a feature, but we settled on the name `--yes` for all other commands. For better consistency, the `uninstall` command should also use `--yes` for this flag.

**Comment by doncicuto** [comment]
Hi @kosmoz can I try this one as my first possible contribution? Thanks!

**Comment by christophenne** [comment]
@doncicuto absolutely, let us know if you need anything!
