### ISSUE TITLE
Gateway API

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#764]
**Package Information**
 - Name: gateway-api
 - Source Code: [if available]
 - Website: [https://gateway-api.sigs.k8s.io/](https://gateway-api.sigs.k8s.io/)

**Why we should add this package to our registry**

**If you are an author of this project, let us know**
 - [ ] I am an author of this project

**Additional information**

[https://gateway-api.sigs.k8s.io/guides/#install-standard-channel](https://gateway-api.sigs.k8s.io/guides/#install-standard-channel)

**Comment by bishalbera** [comment]
Please assign me this @christophenne :)

**Comment by bishalbera** [comment]
@christophenne Hey I've a  question this may sound stupid but I can't help. As I'm new to gateway api I'm a bit confused . Should I just install the gateway api CRD's or a controller which comes with the CRD's?

**Comment by christophenne** [comment]
No worries, I think this package should only include the CRDs, which should be exactly what is done here as well: [https://gateway-api.sigs.k8s.io/guides/#install-standard-channel](https://gateway-api.sigs.k8s.io/guides/#install-standard-channel).

**Comment by bishalbera** [comment]
@christophenne Well great then . Thanks for the info I'll give the update soon :)

**Comment by bishalbera** [comment]
@christophenne Hello so I was trying to test it but hit an error(pics attached below). The error occurred when I ran `make install webhook cert` .  Befor this step I had the server running from the packages directory using `caddy` and also had added a repo called `local`. Any clue what should I do now ? Thanks :)

<img width="1254" alt="Screenshot 2024-06-11 at 11 17 37 AM" src="https://github.com/glasskube/glasskube/assets/123734227/8530749d-e40e-4988-85a5-12453f535db0">

<img width="1710" alt="Screenshot 2024-06-11 at 11 18 43 AM" src="https://github.com/glasskube/glasskube/assets/123734227/54e20525-9f75-4fac-a06c-1bc8147e8d0e">

<img width="1710" alt="Screenshot 2024-06-11 at 11 19 15 AM" src="https://github.com/glasskube/glasskube/assets/123734227/db3e5101-c0be-473f-bfee-338c1f1e72f5">

**Comment by christophenne** [comment]
Are you using minikube? And can you please show more of the error (above what we see in the screenshot)?

It looks to me that the error is coming from when you are trying to start the operator, right? So not from `make install webhook cert` but from `make run`?

**Comment by bishalbera** [comment]
@christophenne Yes I'm using minikube and both the `make run` and `make install webhook cert run` command is giving me the same error . But when I used only `make install webhook cert` it made through I guess. (below are screenshots) 
<img width="1710" alt="Screenshot 2024-06-11 at 3 15 44 PM" src="https://github.com/glasskube/glasskube/assets/123734227/317299c9-a3f1-476d-96c0-ce9950dfca2c">

<img width="1710" alt="Screenshot 2024-06-11 at 3 23 27 PM" src="https://github.com/glasskube/glasskube/assets/123734227/6c322879-a04d-49fc-95f1-5f284efae027">

**Comment by christophenne** [comment]
Rather weird. Which kubernetes version are you running? Btw, you only need `make run` to (re-) start the operator, the other commands are just setup (like the certificate).

**Comment by bishalbera** [comment]
ok @christophenne I'm using v1.30
<img width="1710" alt="Screenshot 2024-06-11 at 3 54 02 PM" src="https://github.com/glasskube/glasskube/assets/123734227/080ceb37-5fb3-420d-a2d5-5a0ac7c45033">

**Comment by christophenne** [comment]
There is no repo delete command yet, so you would have to delete it with `kubectl delete packagerepositories.packages.glasskube.dev local`

**Comment by christophenne** [comment]
As for the other error, it's hard to tell what could be the cause. If you have previously bootstrapped a released version of glasskube in this exact cluster, there might be some conflicts – you could try to create a completely new minikube cluster that you use for development, where you do not "bootstrap", but instead use the make targets (btw, it's easier to use `make setup`) to set everything up.

**Comment by christophenne** [comment]
No you don't need to reinstall. You can use another profile, I usually do it with `minikube start -p dev`.

**Comment by bishalbera** [comment]
@christophenne Hey somehow I sort the error for now. But now I'm getting this error . Can you please help? thanks
![image](https://github.com/glasskube/glasskube/assets/123734227/99198c0a-2e06-4279-9b97-1ef7add75c6a)

**Comment by christophenne** [comment]
Have you started the operator (with `make run`)?

**Comment by bishalbera** [comment]
@christophenne yes I'm getting this in the logs 
![image](https://github.com/glasskube/glasskube/assets/123734227/812197a1-210e-4302-997d-b14ab55cf3d4)

![image](https://github.com/glasskube/glasskube/assets/123734227/9113cdfb-6390-4117-b275-fd0cf869cbc9)
