### ISSUE TITLE
`autoUpdate` output in `glasskube describe --output=[yaml|json]` should be a boolean

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#765]
**Is your feature request related to a problem? Please describe.**
JSON/YAML output to `glasskube describe` has been added in #717. The field `autoUpdate` is a string "Enabled" or "Disabled", but it should actually be a boolean true/false instead.

**Describe the solution you'd like**
`autoUpdate` should be a boolean.

**Describe alternatives you've considered**

**Additional context**
https://github.com/glasskube/glasskube/pull/717#discussion_r1629411787

**Comment by doncicuto** [comment]
Hi @christophenne, it'd be great if you could assign this issue to me, but as my PR #773 is still in review you may prefer that it's merged before I can work on another issue...
