### ISSUE TITLE
Add Creation of Docker Images for Glasskube CLI During Release

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#766]
Some use-cases require running tasks using the Glasskube CLI from within the cluster. To enable those workflows, we need to publish docker images for the Glasskube CLI.

**Comment by hanshal101** [comment]
hey @kosmoz I would like to work on this since this is a new kind of issue, should I complete my previously assigned issue first or you unassigned me from that issue and I'll go for this?

**Comment by kosmoz** [comment]
Hey @hanshal101, I'm sorry to say this but I already started working on this issue and I'm afraid it doesn't make sense to transfer at this point. 

But I noted your feedback and we'll consider keeping issues like this open for contributions in the future!
