### ISSUE TITLE
pull request template URL returns 404Not Found

### ISSUE THREAD

**Issue by mahiro72** [glasskube/glasskube#778]
**Describe the bug**
[pull request template](https://github.com/glasskube/glasskube/blob/main/.github/pull_request_template.md) URL in [the contribution guid](https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md) is returning a 404 Not Found error and needs to be updated.

**To Reproduce**
URL [pull request template](https://github.com/glasskube/glasskube/blob/main/.github/pull_request_template.md) is `404 Not Found error`.

**Expected behavior**
Fix URL https://github.com/glasskube/glasskube/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by mahiro72** [comment]
Is it OK if I work on fixing this issue and updating the URL?

**Comment by pmig** [comment]
yes, sure!
