### ISSUE TITLE
Add Discord link to Glasskube UI footer

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#793]
**Is your feature request related to a problem? Please describe.**
There is currently no link in the Glasskube UI to our Discord server.

**Describe the solution you'd like**
A good place for the Discord link would be in the footer below "Glasskube Cloud"

It should be called "Glasskube Discord" with following link: `https://discord.gg/SxH6KUCGH7`

**Comment by Jaishree2310** [comment]
Hi @pmig can you please assign this to me? 
Thank you!

**Comment by Jaishree2310** [comment]
@pmig can you please help me with the guide to run this after setting it up on my pc?
How to run this?

**Comment by pmig** [comment]
@Jaishree2310 sure you can find the instructions in our [Contributing guidelines](https://github.com/glasskube/glasskube/blob/main/CONTRIBUTING.md)

**Comment by Jaishree2310** [comment]
@pmig I have attached the PR please review it.
Thanks!
