### ISSUE TITLE
Configure eslint for website

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#80]
Docusaurus provides an eslint plugin: https://docusaurus.io/docs/api/misc/@docusaurus/eslint-plugin

Also this article describes how to implement eslint for a react / typescript application: https://dev.to/anukr98/setting-up-eslint-with-tsjs-in-your-react-project-in-2023-57o

**Comment by swastik959** [comment]
I would Like to work on this

**Comment by pmig** [comment]
Thanks @swastik959 if you have any questions regarding the eslint rules, feel free to open a thread on discord.

**Comment by pmig** [comment]
Hi @swastik959 have you already had time to work on the issue? else I would unassigned it again.

**Comment by pmig** [comment]
hi @swastik959 I am removing the assignment now feel free to comment again if you want to work on it.

**Comment by RohanMishra315** [comment]
Hey @pmig Can I have more information about this issue , I'll just do it really quick !

**Comment by pmig** [comment]
Hi @RohanMishra315 [eslint](https://eslint.org/) and [prettier](https://prettier.io/) are not yet configured for our website project. This might lead to inconsistencies across contributors. If you have already experience with these technologies especially in combination with docusaurus this issue is ideal for you.

**Comment by RohanMishra315** [comment]
So we have to add both eslint and prettier, cool. I was just asking the changes made  should be here right   
![Screenshot 2024-02-27 200647](https://github.com/glasskube/glasskube/assets/121561397/97c48b71-5c86-42d4-bbb9-df69d981e25a)

**Comment by pmig** [comment]
@RohanMishra315  yes, but we also need to make sure we can execute `eslint` and `prettier`. There might be a lot of needed changes in order to comply with the latest standard. These can be performed by us in a second step.

**Comment by RohanMishra315** [comment]
Thanks for help @pmig . I'll do the PR real quick.

**Comment by MridulDhiman** [comment]
Hi @pmig, I noticed this issue is still open. I've been exploring solutions and found that using the `eslint/eslintrc` package allows for a backward-compatible `extends` syntax in the ESLint config file. Would this approach be helpful for resolving the issue? I'd appreciate your thoughts on this solution.

**Comment by kosmoz** [comment]
Hey @MridulDhiman! Feel free to give it a shot. I don't think a special package is needed, eslint supports extending configs out of the box. 

Please make sure that you try to use the latest version of eslint, since they somewhat recently released v9 which included some breaking changes. If the docusaurus eslint plugin is not compatible with v9 yet, we can use v8 instead.

https://eslint.org/docs/latest/use/getting-started

**Comment by MridulDhiman** [comment]
@kosmoz Alright! Should I follow a specific standard style guide for the linter configuration, or can I start with a basic configuration?

**Comment by kosmoz** [comment]
We already have some prettier rules in the root `package.json`, which is loosely applied to the website code. The eslint config should not clash with the prettier config. 

Apart from that, I think you can start with a basic config and we can extend it from there.

**Comment by MridulDhiman** [comment]
Hey @kosmoz, I am currently facing an issue. I have configured the linter, and it's behaving completely fine, but whenever we run `eslint .` or `eslint --fix .` script, it shows me a warning of current typescript version being not supported, and prompting me to downgrade it's version. I tried using the `.eslintrc` configuration file as well, but still it gives same warning. I tried downgrading it(typescript) to one of the previous versions (5.2.2) and it shows no error. So, how should I proceed with this?  

![image](https://github.com/glasskube/glasskube/assets/60432617/44953127-a801-4542-809b-dddb9623481f)


| Dependency | Version |
|------------|---------|
| @eslint/js | ^9.5.0 |
| eslint | ^8.57.0 |
| eslint-plugin-import | ^2.29.1 |
| eslint-plugin-prettier | ^5.1.3 |
| eslint-plugin-react | ^7.34.3 |
| globals | ^15.6.0 |
| prettier | ^3.3.2 |
| typescript | ~5.5.0 |
| typescript-eslint | ^7.13.1 |

**Comment by kosmoz** [comment]
Please create a PR with your progress so far, so we can take a look and give some advice

**Comment by MridulDhiman** [comment]
Hey @kosmoz, thank you for your help. I've updated the typescript-eslint to the latest version, which resolved the TypeScript version compatibility warning. I've created a pull request with these changes and would appreciate your review when you have a moment.

**Comment by kosmoz** [comment]
Did you fix the warning? Because I don't see it

**Comment by MridulDhiman** [comment]
Yes, warning was removed, as I updated `typescript-eslint` package from v7.13.1 to v7.14.1.
