### ISSUE TITLE
Add recent blog posts section to website front page

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#800]
**Is your feature request related to a problem? Please describe.**
We just redesigned our front page of [glasskube.dev](https://glasskube.dev/) and publish [blog posts](https://glasskube.dev/blog/) regularly, but the latest posts are not visible on the website.

**Describe the solution you'd like**
Add a recent blog post section to the front-page, similar to the [cyclops](https://cyclops-ui.com/) website:

![image](https://github.com/glasskube/glasskube/assets/3041752/5dc2ad51-e0d3-4a76-8e31-5ea9815e668e)

**Additional context**
The blog posts should be fetched dynamically.

**Comment by Aryakoste** [comment]
Hello @pmig I would like to work on this issue.

**Comment by pmig** [comment]
Sure, if you have any questions feel free to join our discord ☺️

**Comment by Aryakoste** [comment]
Hello @pmig @kosmoz I have completed the UI just the dynamic part is remaining. I have tried using docusaurus-plugin-content-blog plugin to extract the data but it isnt working. If i add customFields in the docusaurus.config.ts with blogPosts then i can access the data but we can't change it dynamically. I have tried experimenting with different plugins and hooks too. I have tried it file system to access files and content but ofc its not a good method. What are your suggestions.

**Comment by Aryakoste** [comment]
The plugin hooks i tried returns data as null even if they are configured correctly in docusaurus.config.ts.

**Comment by kosmoz** [comment]
I don't know, it seems like this is not directly supported by the tech stack that is used by Docusaurus, but I found this discussion which might be helpful: https://github.com/facebook/docusaurus/discussions/6423

**Comment by Aryakoste** [comment]
Yeah this is helpful. It will work. Will implement this and will submit the PR. Thanks.

**Comment by Aryakoste** [comment]
For this to work I would have to delete the pages/index.tsx because i am defining custom path in custom-blog-plugin.js for "/". This way i can get the blogs data in the Home page defined in components. It is written here too:-
[https://kgajera.com/blog/display-recent-blog-posts-on-home-page-with-docusaurus/](url)

So is it ok if i do that. And one more question the Images that we show inside the blogs. I think we will have to define it in frontmatter or meta data of mdx pages. Because i am getting the images url in content i think it will be hard to extract it from there.

@kosmoz @pmig

**Comment by Aryakoste** [comment]
I tried adding that reference but it isn't passing blogsData as a props there. And it still shows path "/" is getting overwrite. Because when you define pages/index.tsx it takes that page as path for "/".

**Comment by kosmoz** [comment]
OK, I think I understand. But can't we then just rename it to "home.tsx" or something like that?

**Comment by Aryakoste** [comment]
Ok will try that I think this will work too.

**Comment by Aryakoste** [comment]
Hello. Now i am getting all the data but one thing remains that i mentioned here 
https://github.com/glasskube/glasskube/issues/800#issuecomment-2171695094

I am not able to get the thumbnail images for blogs i directly get the content. So should we mention the image urls in frontMatter. 
 Below is the data I get:-

**Comment by Aryakoste** [comment]
{
  "metadata": {
    "title": "Why nobody grows up wanting to be a DevOps engineer",
    "description": "How did DevOps start, what were it's initial promises and where are we going?",
    "frontMatter": {
      "slug": "future-of-devops",
      "title": "Why nobody grows up wanting to be a DevOps engineer",
      "description": "How did DevOps start, what were it's initial promises and where are we going?",
      "authors": [
        "jpage"
      ],
      "tags": [
        "glasskube"
      ]
    }
  }
}

**Comment by Aryakoste** [comment]
Hello. Now i am getting all the data but one thing remains that i mentioned here
https://github.com/glasskube/glasskube/issues/800#issuecomment-2171695094

I am not able to get the thumbnail images for blogs i directly get the content. So should we mention the image urls in frontMatter.

**Comment by kosmoz** [comment]
Yes, please try that!
