### ISSUE TITLE
`repo add` command with --default flag should return an error if there's a repository with that annotation already

### ISSUE THREAD

**Issue by doncicuto** [glasskube/glasskube#806]
**Describe the bug**
[Documentation](https://glasskube.dev/docs/design/repositories/#repository-management) states that if you use --default with the `repo add` command it should return an error if there's a repository with that annotation already.

**To Reproduce**
1. Try to add a new repository with `glasskube repo add test https://example.com --default`
2. List repositories with `glasskube repo list`
3. Check that there are two default repositories

**Expected behavior**
Either we should get an error, or instead the current default repo will get the default annotation removed and the new repository being added will be the new default repo

**Screenshots**

![image](https://github.com/glasskube/glasskube/assets/30386061/c44c7386-bdba-4293-9042-94f2e7a9ab8a)

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: 1.30.0
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.0.1
 - CLI version: dev

**Comment by doncicuto** [comment]
If you agree, once the triage is performed, I could take this issue as it's related with #682 and I could reuse the code if the PR associated gets merged after review. Thanks!

**Comment by hanshal101** [comment]
Can I pick this up?

**Comment by doncicuto** [comment]
Hi @hanshal101, as I've opened this issue and worked in #682 I thought, if you don't mind and the project leaders agree, that I could continue with the code for this issue as I was just waiting that @kosmoz and @christophenne could have more time to triage this issue and assign it. It's great that this project has so many contributors willing to participate :smile:

**Comment by hanshal101** [comment]
Ohh sorry I didn't noticed the PR. Cool

**Comment by christophenne** [comment]
Yes, sorry we forgot to assign you.
