### ISSUE TITLE
Create category link for website guide section

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#81]
We currently use the auto generated side bar in the docs section.

It would be nice for our guides to have an auto generated category index page: https://docusaurus.io/docs/sidebar/items#category-link

**Comment by UtkarshUmre** [comment]
i would like to work on this !

**Comment by pmig** [comment]
sure, please go ahead

**Comment by jakepage91** [comment]
I can take this @pmig

**Comment by pmig** [comment]
Sure @jakepage91 - please go ahead.

I did something similar in this PR as an inspiration: https://github.com/cyclops-ui/cyclops/pull/120
