### ISSUE TITLE
Quickwit package: separation of metastoreUri and defaultIndexUri

### ISSUE THREAD

**Issue by idrissneumann** [glasskube/glasskube#818]
Hi.

**Is your feature request related to a problem? Please describe.**

On some installations of quickwit, the metastoreUri isn't the same value as the default index uri (which is an object storage bucket). So we should have two separate fields even if it's the same value sometimes.

It'll help the quickwit users to understand the mapping with the helmchart better and also be able to add an external postgreSQL in their cluster to tune the quickwit performances later.

**Describe the solution you'd like**

Two separate fields `metastoreUri` and `s3Uri`

Thanks in advance

**Comment by idrissneumann** [comment]
I have open this pull request: https://github.com/glasskube/packages/pull/150

**Comment by kosmoz** [comment]
Closed by https://github.com/glasskube/packages/pull/150
