### ISSUE TITLE
Links in package description should open in new tab

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#832]
**Is your feature request related to a problem? Please describe.**
The `longDescription` of a package manifest can contain links in markdown format. A markdown link is correctly rendered as an html anchor element, but it opens in the same tab the user is currently in.

**Describe the solution you'd like**
Links in the `longDescription` should be rendered to have the `target="_blank"` attribute too, to make it open in a new tab.

**Describe alternatives you've considered**

**Additional context**
This description is converted from markdown to HTML on the `package.html` template, using the `| Markdown` pipe. The corresponding function `Markdown` is registered in the `templates.go` file. There, the rendering happens – probably here something has to be done.

**Comment by doncicuto** [comment]
Hi @christophenne may I take this one?
