### ISSUE TITLE
Use a different port for "glasskube serve" when default port is already in use

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#84]
If the app fails to bind to port 8085 (the default port), it should prompt the user if it should use a different port. The operating system should assign the listener an arbitrary new port, which can be achieved by trying to listen on port `0`. In order to also be able to retrieve the used port later, `http.ListenAndServe` must be replaced with subsequent calls of `net.Listen` and `http.Serve`.

```
$ glasskube serve
Port 8580 is already in use.
Should glasskube use a different port? (Y/n)
```

If a custom port was specified via `--port`, the app should just `Exit(1)` instead.

**Comment by fykaa** [comment]
Would like to work on this
