### ISSUE TITLE
Add upgrade instruction section to the upgrading doc (for macOS, Linux and Windows)

### ISSUE THREAD

**Issue by jakepage91** [glasskube/glasskube#845]
**Is your feature request related to a problem? Please describe.**
Glasskube installation and upgrading are detailed in the documentation. However, the current MacOS installation method does not include instructions for upgrading Glasskube using Homebrew.

To upgrade Glasskube, use the following command:
```
brew upgrade glasskube
```
Also add the upgrading steps for Linux and Windows, which requires downloading the latest binary and reinstalling Glasskube.

We should add a section to the [Upgrading page](https://glasskube.dev/docs/getting-started/upgrading/) ) to include this Homebrew upgrade method.

**Comment by Harshitk-cp** [comment]
hey @jakepage91 I'd like to work on this.

**Comment by jakepage91** [comment]
All yours @Harshitk-cp !

**Comment by Harshitk-cp** [comment]
@jakepage91 ^^
