### ISSUE TITLE
Native html validation seems to be broken

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#849]
**Describe the bug**
Html form validation is broken

**To Reproduce**
1. open the ui `glasskube open`
2. configure a package with a mandatory configuration values (e.g. `k8sgpt-operator`)
3. save a package without entering a mandatory value

**Expected behavior**
Html validation should work

**Screenshots**
![image](https://github.com/glasskube/glasskube/assets/3041752/0e592624-c600-4ad9-a644-7bd3493bc992)

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: 1.30.0
 - Provider: minikube

**Glasskube Info (please complete the following information):**
```
at 14:29:49 ➜ glasskube version
glasskube: v0.10.0
package-operator: v0.10.0
```

**Additional context**
- This is a regression.
- The required attribute should be added if a configuration value is marked as required

**Comment by christophenne** [comment]
Some technical context:

* you can find all the input templates for the configuration page in `internal/web/templates/components/pkg-config.input.html`
* required validation works for html option elements (dropdown), see `pkg-config-input-options`
* it's the same for number and text inputs, but for some reason just missing there. it should be added to these two input types too.

**Comment by rharshit82** [comment]
Have added this in the same PR that added asterisks. I found this bug while doing review changes.
