### ISSUE TITLE
Add asterisks to input label for required configuration values

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#850]
**Is your feature request related to a problem? Please describe.**
It is not easily possible to determine if an configuration value is mandatory.

**Describe the solution you'd like**
If a configuration value as marked as mandatory an asteriks should be added to the label

**Describe alternatives you've considered**
None, open for suggestions

**Additional context**
 - Bootstrap 5 related documentation: https://getbootstrap.com/docs/5.3/forms/validation/
 - Example solution of an asterisk: https://stackoverflow.com/questions/23141854/adding-asterisk-to-required-fields-in-bootstrap-3
 - related to https://github.com/glasskube/glasskube/issues/849

**Comment by rharshit82** [comment]
Can you please assign me this ?
