### ISSUE TITLE
Repository configuration via UI backend

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#861]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to add and update repository via the `cli`.

**Describe the solution you'd like**
When clicking on a repository a detail page should be shown (similar to `ClusterPackages`) where a user can configure the name, url and checkbox if the repo is the default repo.

Additionally there should be button to add a new repository in the top right corner.

The scope of this ticket is to create the golang backend to receive the form request from the frontend and process it similar to how the cli processes it.

**Additional context**
Related frontend issue: https://github.com/glasskube/glasskube/issues/860
Design specification: https://glasskube.dev/docs/design/repositories/

**Comment by STAR-173** [comment]
Hey @pmig , I would like to take on this. But I believe I will require a bit of guidance

**Comment by kosmoz** [comment]
Hey @STAR-173, how are you doing? Do you need any help with this issue?

**Comment by STAR-173** [comment]
Hii @kosmoz,
I went through the `repo_add` and `repo_update` files. Was waiting for someone to take on the frontend part so could better co-ordinate with them
Also, I got a bit busy during this week. Will continue working on this during this weekend.

**Comment by STAR-173** [comment]
Hi @kosmoz, 
I was working on backend taking reference from the cli version `repo_add.go`.
I noticed that you are using a few methods like `Normalize` and `SetAuth` which seems to do some error checking and other things. 
I noticed that these methods are also using some `username` and `password` param. I have no idea on this. Could you tell me a little bit about them and do i need to include them in the backend error checks ?

**Comment by kosmoz** [comment]
> I noticed that you are using a few methods like `Normalize` and `SetAuth` which seems to do some error checking and other things. 

The `SetAuth` method you are refering to looks more complicated than it is because of the different ways CLI flags can be used for this feature. It is not relevant to the UI implementation of the feature. 

> I noticed that these methods are also using some `username` and `password` param. I have no idea on this. Could you tell me a little bit about them and do i need to include them in the backend error checks ?

Glasskube Repositories support authenticated modes via `Basic` (aka. "username/password") and `Bearer` (aka "token") authentication modes. But as @christophenne said, I think it would be fair to skip this part for now. We can implement it in a separate issue.

**Comment by kosmoz** [comment]
Hey @STAR-173, any update on this issue? If you have further questions, let us know!

**Comment by kosmoz** [comment]
Hey @STAR-173, I've unassigned you due to inactivity

**Comment by prikshitsingh24** [comment]
If nobody is working on this, can I take this issue?

**Comment by prikshitsingh24** [comment]
ok

**Comment by prikshitsingh24** [comment]
If the issue #860 is stuck and if you will allow me I can create a patch for that issue in the mean time.

**Comment by prikshitsingh24** [comment]
Yes I will do my best.
