### ISSUE TITLE
UI should have a sticky header

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#863]
**Is your feature request related to a problem? Please describe.**
The UI currently has a header, but when the page is too long and the user scrolls down, the header is not visible anymore.

**Describe the solution you'd like**
The UI should show the header at all times (sticky header), even if the user scrolled down. 

**Additional context**
The bootstrap position helpers probably help: https://getbootstrap.com/docs/5.3/helpers/position

**Comment by oversampling** [comment]
Hi, I can handle this issue, do you mind to assign this issue to me.
