### ISSUE TITLE
CLI: Add support for changing configuration during update

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#864]
**Is your feature request related to a problem? Please describe.**
If the value definitions of a package are different between versions, it is sometimes not possible to update safely. Particularly, if a new required value is added, it is not possible to update at all.

**Describe the solution you'd like**
When running `glasskube update` to update a package with configuration values, the user should be asked if they want to change the configuration. If they answer yes, the configuration wizard should be started.

**Comment by kosmoz** [comment]
Hey @Harshitk-cp! I would be happy to assign you this issue once your other PRs are approved and merged. Due to a recent influx of external contributions, PR reviews can take a little longer than usual, so please have some patience until we get to yours :pray:

**Comment by Harshitk-cp** [comment]
hey! got a PR merged yesterday might i pick this up now?

**Comment by Harshitk-cp** [comment]
@kosmoz can you give bit more detail on this? also how does the configuration wizard updates the value definitions of the package, is it implemented somewhere?

**Comment by kosmoz** [comment]
I imagine it something like this (pseudo code):

```
For each package to be updated:
  Fetch the manifest for the new version
  If it has at least one value definition:
    Ask the user if they want to update the configuration
    If they agree run the config wizard (see below)
```

For an example, take a look at cmd/glasskube/cmd/configure.go:

https://github.com/glasskube/glasskube/blob/9b6f854396a229d76adb0512aa259b8a2bb8a8a2/cmd/glasskube/cmd/configure.go#L60-L68
