### ISSUE TITLE
CLI: Add support for listing all packages for a package name

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#865]
### Is your feature request related to a problem? Please describe.
`glasskube list` shows the list of all ClusterPackages or Packages or both. It should also be possible to list all packages with a particular `.Spec.PackageInfo.Name`.

### Describe the solution you'd like
When `glasskube list` is called with an argument, only the `Package`s with that `.Spec.PackageInfo.Name` should be listed. 

#### Examples

```sh
# shows a list of all Package resources with .Spec.PackageInfo.Name == "quickwit"
glasskube list quickwit
```
```sh
# shows a list of all Package resources in namespace "foo" with .Spec.PackageInfo.Name == "quickwit"
glasskube list quickwit --namespace foo
```
```sh
# shows an error message and call ExitWithError
glasskube list quickwit --kind clusterpackage
```

#### More details
- This operational mode is defined by `len(args) > 0`
- This mode implies that only namespace-scoped `Package`s should be shown, no `ClusterPackage`s (like `--kind package`). 
- In this mode, using the `--kind` flag is an error

**Comment by kanha-gupta** [comment]
I'll take this

**Comment by kosmoz** [comment]
Hi @kanha-gupta! This is sort of blocked by an open PR (https://github.com/glasskube/glasskube/pull/817), so I think it would make sense to wait a couple of days before this should be tackled. I'll let you know once it's ready. In the meantime, feel free to explore our other open issues. :slightly_smiling_face:

**Comment by kosmoz** [comment]
Hey @kanha-gupta! This issue can now be worked on. If you're still interested, I can assign you. Just let me know!

**Comment by oversampling** [comment]
@kosmoz If nobody work on this, I can work on this.

**Comment by kanha-gupta** [comment]
Sure I'll pick this. @oversampling do you want to work ?

**Comment by oversampling** [comment]
> Sure I'll pick this. @oversampling do you want to work ?

Is ok, you can take this.

**Comment by kanha-gupta** [comment]
Hi @kosmoz  @oversampling I had an unexpected travel therefore It would cause delay.
I encourage the community to take this :)

**Comment by kosmoz** [comment]
> Hi @kosmoz @oversampling I had an unexpected travel therefore It would cause delay. I encourage the community to take this :)

No problem, thanks for letting us know. Safe travels!

**Comment by yeahservice** [comment]
@kosmoz I would be happy to take this one

**Comment by yeahservice** [comment]
@kosmoz I have created the PR as draft, because there are some suggested changes I would like to have some feedback on first. More details in the "Additional Information" section of the PR
