### ISSUE TITLE
`glasskube configure` should show special message when there are no values to configure

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#867]
When a package has no configuration values, the `glasskube configure` command should show "This package has no configuration values" and quit. 

Example: `glasskube configure cert-manager`.

**Comment by CroWzblooD** [comment]
I would like to work on it

**Comment by christophenne** [comment]
@CroWzblooD how is it going here, do you need any help/guidance?

**Comment by suprasauce** [comment]
@christophenne Can I get assigned on this?

**Comment by suprasauce** [comment]
Hi @christophenne Will be away for a week, completely unplanned. If anyone else wants to take this up they can.
Thanks

**Comment by christophenne** [comment]
Hey @suprasauce thanks for letting us know!

**Comment by utsab818** [comment]
@christophenne Can I try this issue?

**Comment by utsab818** [comment]
@christophenne Would you please guide me on testing this feature. How do I change the configuration value to set it to no values?

**Comment by christophenne** [comment]
@utsab818 this doesn't have to with a value being null, it's about packages that don't have any configuration values in their manifest, for example `cert-manager`. So you can run `glasskube configure cert-manager` and it should show the special message.

**Comment by utsab818** [comment]
@christophenne Thanks! Got it.

**Comment by Arsh0023** [comment]
Hey @christophenne, if no ones working can I take this issue ?
