### ISSUE TITLE
Remove `(Beta Version)` label from README.md

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#869]
**Describe the solution you'd like**
As Glasskube becomes more mature we can less prominent indicate that we are not yet API stable. (as we are still in the v0.x release phase).

**Describe alternatives you've considered**
The scope of this ticket is to remove ` (Beta Version)` from the h3.

**Additional context**

**Comment by CroWzblooD** [comment]
Hey i would like to work on this

**Comment by Dnyaneshpise** [comment]
do we have to only remove this (Beta Version) from h3 here
![Screenshot 2024-07-04 161618](https://github.com/glasskube/glasskube/assets/93508573/3775bdb4-ac82-467f-b72a-ba5f344280ab)

**Comment by christophenne** [comment]
@Dnyaneshpise yes – wanna try it?

**Comment by Srikrishnabh** [comment]
@christophenne raised PR : https://github.com/glasskube/glasskube/pull/964

**Comment by Dnyaneshpise** [comment]
> @Dnyaneshpise yes – wanna try it?

Yes ! , I have created PR for this issue please check.
