### ISSUE TITLE
`glasskube version` ascii art

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#870]
**Is your feature request related to a problem? Please describe.**
The `glasskube version` command shows the versions of the CLI and package operator.

**Describe the solution you'd like**
It would be nice if the version command also shows a nice ascii art of the text `Glasskube` at the top of the output. 

**Additional context**
https://www.asciiart.eu/

**Comment by WaterLemons2k** [comment]
I would like to work on this issue, can someone assign it to me? Thanks!

**Comment by pmig** [comment]
Hi @WaterLemons2k - Our `good first issues` are primarily focused for first time contributors. So I am leaving it unassigned for the time being.

**Comment by Harshitk-cp** [comment]
can i get assigned to this?

**Comment by Harshitk-cp** [comment]
Using this [library](https://github.com/common-nighthawk/go-figure) for ascii
Let me know the font and any animation or if we need something custom.

<img width="592" alt="Screenshot 2024-06-26 at 2 00 25 AM" src="https://github.com/glasskube/glasskube/assets/67193749/a056c305-d2e7-4d5c-954f-91375a07d1e9">
