### ISSUE TITLE
Webhook Validator for `PackageRepository` deletion

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#871]
**Is your feature request related to a problem? Please describe.**
`PackageRepository` resources can be deleted, even if there are packages installed from that repository.

**Describe the solution you'd like**
There should be a webhook validator in the operator, that, when a `PackageRepository` is about to be deleted, should check whether there are no packages installed from that repository. There should be a validation error, if packages from the repo are still installed. 

**Additional context**
There are already some webhook validations in place, e.g. for `ClusterPackage` resources.

**Comment by hanshal101** [comment]
Hey @christophenne I would like to work on this

**Comment by hanshal101** [comment]
Just for Clarification:

correct me if I'm wrong.
Here I do the following steps:

- Define the Webhook Configuration like this: https://github.com/glasskube/glasskube/blob/d7ce5fa72434e93720a9681279e8ad3e5e058cfe/config/webhook/manifests.yaml
- Implement the Webhook Server: make all the logic of webhook
- Deploy the Webhook Server: i.e make the deployment and the service for the webhook
- Integrate Webhook with the Operator: same as ClusterPaackages
- -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by christophenne** [comment]
@hanshal101 please make yourself familiar with kubebuilder: https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation especially the webhook session. In our code you can have a look at `internal/webhook/package_validator.go` – there you see the actual implementation. The important thing to figure out is how the webhook is registered/wired to be actually called by the kubernetes API – I also don't know that yet and will try to find out, the answer is somewhere in the codebase. I'm just pretty sure that the webhook manifests you linked to, are generated by kubebuilder (probably the `make controller-gen` command).

**Comment by rakshitgondwal** [comment]
Hey @hanshal101, are you working on this?

**Comment by hanshal101** [comment]
hey @christophenne I'm so sorry I'm still not clear about this issue, I can surely give it a try but will take some time. If this issue is on a priority basis you can unassign me.

**Comment by christophenne** [comment]
@hanshal101 no worries, it's also not super high priority. I will unassign you but of course you can still work on it or try around with it.

**Comment by hanshal101** [comment]
Thanks @christophenne I won't work officially on this so can I create a draft PR just to try?

**Comment by yeahservice** [comment]
@christophenne I would be happy to work on this. @hanshal101 maybe we can collaborate on it?

**Comment by hanshal101** [comment]
> @christophenne I would be happy to work on this. @hanshal101 maybe we can collaborate on it?

works for me

**Comment by christophenne** [comment]
great, good idea :)
