### ISSUE TITLE
Exchange AsciinemaPlayer demo on website with actual demo video from youtube

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#873]
**Is your feature request related to a problem? Please describe.**
The AsciinemaPlayer got outdated and glasskube already introduced an UI.

**Describe the solution you'd like**
Exchange the `AsciinemaPlayer` component with an YouTube embed of: https://www.youtube.com/watch?v=aIeTHGWsG2c
The youtube video should be embedded similar to we embed videos on our blog: https://glasskube.dev/blog/release-v0.1.0/
Also the Asciinema Player and dependency should removed after the change.

**Additional context**
The video is already linked in the README.md

**Comment by MridulDhiman** [comment]
Hey @pmig, I would like to contribute to this issue
