### ISSUE TITLE
Fix CSS Minimizer Warnings in Website Build

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#880]
When building the website by running `npm run build` in the `website` directory, the following warnings are shown:
```
[WARNING] {"file":"assets/css/styles.cb46e6fd.css","message":"assets/css/styles.cb46e6fd.css from Css Minimizer plugin\nUnexpected '}' at assets/css/styles.cb46e6fd.css:25:42359.","compilerPath":"client"}
[WARNING] {"file":"assets/css/styles.cb46e6fd.css","message":"assets/css/styles.cb46e6fd.css from Css Minimizer plugin\nInvalid property name 'h2{text-shadow' at assets/css/styles.cb46e6fd.css:25:42314. Ignoring.","compilerPath":"client"}
```

This is probably related to the `text-shadow` applied to `h2` elements.

**Comment by Jaishree2310** [comment]
Hey @kosmoz  can you assign this issue to me?
Thanks!!

**Comment by kosmoz** [comment]
Hey @Jaishree2310, how are you doing? Do you need any help with this issue?

**Comment by Jaishree2310** [comment]
> Hey @Jaishree2310, how are you doing? Do you need any help with this issue?

Hi, I will raise a PR soon.
Thank you!

**Comment by kosmoz** [comment]
Hey @Jaishree2310, I've unassigned you due to inactivity. If you are still interested in contributing, please have a look at our [open issues](https://github.com/glasskube/glasskube/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee) and let us know if anything piques your interest.

**Comment by anishbista60** [comment]
@kosmoz Could you please look into this PR ? Looks good for me.
