### ISSUE TITLE
Fix Broken Links in Website

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#881]
When building the website by running `npm run build` in the `website` directory, some broken links are found:
```
Exhaustive list of all broken links found:
- Broken link on source page path = /guides/cert-manager/:
   -> linking to ./ingress-nginx/ (resolved as: /guides/cert-manager/ingress-nginx/)
- Broken link on source page path = /guides/ingress-nginx/:
   -> linking to ./cert-manager/ (resolved as: /guides/ingress-nginx/cert-manager/)
```

**Comment by Shubham9123** [comment]
Hi, can you assign me this issue?

**Comment by STAR-173** [comment]
Hey @kosmoz , sorry for not informing you but I was already working on the issue.

**Comment by kosmoz** [comment]
@STAR-173 next time please let us know beforehand, so we can avoid duplicate work. Otherwise it is not fair to your fellow contributors. 

Sorry for this @Shubham9123, please feel free to explore our other open issues!
