### ISSUE TITLE
Migrate all embedded youtube videos to the youtube-nocookie domain

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#884]
**Is your feature request related to a problem? Please describe.**
We currently have a mix of youtube embeds with [youtube](https://github.com/search?q=repo%3Aglasskube%2Fglasskube%20www.youtube.com&type=code) and the [youtube-nocookie](https://github.com/search?q=repo%3Aglasskube%2Fglasskube+www.youtube-nocookie.com&type=code) domain.

**Describe the solution you'd like**
Only use the youtube-nocookie domain.

**Additional context**
This is also relevant for new embeds

**Comment by STAR-173** [comment]
Hey @pmig , Should I work on this issue ?

**Comment by STAR-173** [comment]
Hey @pmig , while going through the mdx file, I noticed that the `<iframe>` tag is not working as intended. Instead it is just rendering the tag as a plain text.
Should I fix this also ?
