### ISSUE TITLE
The website shows the Community Ingress controller using NGINX Ingress Controllers logo.

### ISSUE THREAD

**Issue by j1m-ryan** [glasskube/glasskube#887]
**Describe the bug**
These are two different projects. The logo for this project `nginxinc/kubernetes-ingress` is being used as a logo for `kubernetes/ingress-nginx`

**To Reproduce**
1. Go to https://glasskube.dev/packages/
2. Scroll down till you see ingress-NGINX
3. See NGINX Ingress Controller's logo.

**Comment by kosmoz** [comment]
Uh this one definitely slipped though. Thanks for reporting!

**Comment by Aashish1-1-1** [comment]
@kosmoz can i solve this? if yes how do i get internal iconUrl

**Comment by Aashish1-1-1** [comment]
@kosmoz in github repo i found that kubernetes/ingress-nginx have same logo as kubernetes/dashboard so replaced can you check
