### ISSUE TITLE
Uninstalling bootstrap?

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#893]
**Is your feature request related to a problem? Please describe.**

I cannot find a clear way to uninstall the bootstrap / operator.

**Describe the solution you'd like**

Ability to uninstall bootstrap

**Describe alternatives you've considered**

Going through --help / documentation.

**Additional context**

N/A

**Comment by kosmoz** [comment]
You can use the `purge` command for this. I just noticed that it appears to be missing from the documentation. Check `glasskube help purge` for more info
