### ISSUE TITLE
No warnings that telemetry is installing.

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#895]
**Is your feature request related to a problem? Please describe.**

When doing `glasskube bootstrap` there is ZERO warnings that telemetry will be populated.

It also installs this with the telemetry config enabled within the cluster config.

This isn't cool as it's a big privacy concern with company kubernetes clusters.

**Describe the solution you'd like**

Telemetry warning / "we are installing telemetry on your cluster" when using bootstrap

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by pmig** [comment]
As commented on the linked issue - we try to be very open about what data we collect: https://glasskube.dev/docs/design/telemetry/

This hint is definitely reasonable. Altoutgh I would prefer a message that encourages users to keep sending telemetry data. Similar to "You will be contributing to Glasskube by sending anonymous telemetry data. Find more information in our documentation"

**Comment by sratslla** [comment]
I would like to work on this!

**Comment by pmig** [comment]
@sratslla this issue does not have the help wanted label, see:

 - https://github.com/glasskube/glasskube/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
