### ISSUE TITLE
Documentation is confusing regarding cluster telemetry uninstallation.

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#896]
**Is your feature request related to a problem? Please describe.**

In the docs it says: https://github.com/glasskube/glasskube/blob/c7e139ffc89cb93a76066c475b92dce0c86fcf22/website/docs/04_design/telemetry.md?plain=1#L49C1-L49C105

The information about whether telemetry is enabled or not, is stored **once per cluster installation**. 

Basically I did:
1. Install with `glasskube bootstrap`
2. Realized "oh no there is telemetry"
3. Did:
```
glasskube telemetry disable

Glasskube telemetry is now disabled for cluster default.
```
4. Realized in the docs it's only stored once per cluster installation
5. Think it's actually disabled
6. Go to uninstall bootstrap so I can re-install with telemetry disabled
7. Unable to uninstall bootstrap (see #893 )

**Describe the solution you'd like**

More clear documentation?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by kosmoz** [comment]
I think I understand your confusion. It's supposed to mean that the setting is stored on the cluster. But I agree that it can be misunderstood to mean it can only be set during installation.

What you did was correct, `glasskube telemetry disable` disables telemetry for that cluster.
