### ISSUE TITLE
The `--no-progress` flag is ignored by the `glasskube bootstrap` command

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#900]
**Describe the bug**

Doing:

```
gk bootstrap --no-progress --non-interactive --yes -o yaml > foobar.yaml
⚠️  Glasskube is already installed in this cluster (default) in version v0.11.0. You are about to bootstrap this version again.

## Installing GLASSKUBE ##
🧊 The next generation Package Manager for Kubernetes 📦
* Fetching Glasskube manifest from https://github.com/glasskube/glasskube/releases/download/v0.11.0/manifest-aio.yaml
* Validating existing installation
* Applying Glasskube manifests
```

**To Reproduce**
Do the above command

**Expected behavior**

I expect no other input, just the YAML. Yet I get:
```
⚠️  Glasskube is already installed in this cluster (default) in version v0.11.0. You are about to bootstrap this version again.

## Installing GLASSKUBE ##
🧊 The next generation Package Manager for Kubernetes 📦
* Fetching Glasskube manifest from https://github.com/glasskube/glasskube/releases/download/v0.11.0/manifest-aio.yaml
* Validating existing installation
* Applying Glasskube manifests
```

**Screenshots**

N/A

**Cluster Info (please complete the following information):**

N/A

**Glasskube Info (please complete the following information):**
```
▶ gk version
Error checking PackageOperator version:

deployments.apps "glasskube-controller-manager" not found

  ____ _        _    ____ ____  _  ___   _ ____  _____
 / ___| |      / \  / ___/ ___|| |/ / | | | __ )| ____|
| |  _| |     / _ \ \___ \___ \| ' /| | | |  _ \|  _|
| |_| | |___ / ___ \ ___) |__) | . \| |_| | |_) | |___
 \____|_____/_/   \_\____/____/|_|\_\\___/|____/|_____|

glasskube: v0.11.0
package-operator: not installed
Glasskube is not yet bootstrapped. Use 'glasskube bootstrap' to get started.
```

**Comment by kosmoz** [comment]
Thanks @cdrage, this is definitely an issue. It appears that this is only applies to the `bootstrap` command (correct me if I'm wrong), so I updated the title accordingly.

**Comment by rharshit82** [comment]
Can you please assign me this ?

**Comment by kosmoz** [comment]
Hey @rharshit82! I noticed that there is still a PR of yours that has some unresolved comments. Let's please finish that first, afterwards I'll gladly assign you!

**Comment by rharshit82** [comment]
Now can you please assign me this?

**Comment by rharshit82** [comment]
I will raise PR for this by Friday

**Comment by kosmoz** [comment]
> Unfortunately I am not able to take out time to complete this PR. Will have to rebase it since there are many merge conflicts that need to be resolved. Once that is done, extra removals of progress output has to be removed and PR will be ready.
> 
> Would be better if someone else picks this. If someone doesn't pick this, I will complete it next weekend.

OK, no problem and thanks for letting us know!

**Comment by suprasauce** [comment]
@kosmoz Can I get assigned on this?

**Comment by suprasauce** [comment]
@kosmoz does the following message count as progress? Isn't this a warning? By analyzing the other commands it seems that the --no-progress flag disables the spinner, not the warnings/ error's.
```
⚠️  Glasskube is already installed in this cluster (default) in version v0.11.0. You are about to bootstrap this version again.
```
If the above is true, do we expect the following output?
```
gk bootstrap --no-progress --non-interactive --yes -o yaml > foobar.yaml
⚠️  Glasskube is already installed in this cluster (default) in version v0.11.0. You are about to bootstrap this version again.
```

**Comment by suprasauce** [comment]
@kosmoz Thanks for the clarification, I have raised a PR #1007
