### ISSUE TITLE
Auto-Update is not shown on discussion page

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#905]
**Describe the bug**
The package detail page and package discussion page share the same header template, which includes logo, name, and the badges showing installation information (version, repo, auto-update). However, on the discussion page, the auto-update value is empty, while on the package detail page it say "Disabled" or "Enabled". 

**To Reproduce**
1. Go to the package detail page of an installed package
2. Click on the discussion badge to get to the discussion page

**Expected behavior**
Auto update value should be the same as on package detail page. 

**Screenshots**

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: 1.30
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.10.1
 - CLI version: dev (not released yet)

**Additional context**

**Comment by rharshit82** [comment]
Since this was a minor change and very less time passed since the issue was raised, didn't ask earlier. Can you please assign me this?

**Comment by christophenne** [comment]
Sure, thanks, I'll take a look soon.
