### ISSUE TITLE
Display status message in `glasskube describe` command

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#927]
**Is your feature request related to a problem? Please describe.**
Like #899, but for the describe command of a package.

**Describe the solution you'd like**
Message should be shown below the status, but non-installed packages should not show it at all.

**Additional context**
#899

**Comment by ankitsridhar16** [comment]
I would like to work on this issue

**Comment by ankitsridhar16** [comment]
in case if the condition is `Failed` do we show the message ?

**Comment by ankitsridhar16** [comment]
@christophenne I have created a draft PR can you take a look and suggest me necessary improvements and changes
