### ISSUE TITLE
`glasskube ls --kind package` should also support `-o` flag

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#928]
**Is your feature request related to a problem? Please describe.**
`-o` (output) flag is not yet implemented for listing packages, only for clusterpackages.

**Describe the solution you'd like**
Similar to `glasskube ls --kind clusterpackage` the command should also support `yaml` and `json` output for packages.

**Comment by Arsh0023** [comment]
Hi @christophenne, can I take this issue ?
