### ISSUE TITLE
Consistent uppercase description for command flags

### ISSUE THREAD

**Issue by doncicuto** [glasskube/glasskube#941]
Right now glasskube command has no consistent way of showing flags descriptions. A mix of uppercase and lowercase descriptions are shown. 

![image](https://github.com/glasskube/glasskube/assets/30386061/05b0001d-39ad-483d-9e3f-9ba3b1aae9ae)

![image](https://github.com/glasskube/glasskube/assets/30386061/a524d7b2-52a0-4d49-9300-7770c5b98677)

I think we should offer an uppercase description for any command flag.

I'd like to have the opportunity to fix this issue but I understand that you may offer it as a good-first-issue

**Comment by christophenne** [comment]
Thanks @doncicuto, I think it's a perfect good-first-issue :)

**Comment by bitsundae** [comment]
Hi, I would like to do this.

**Comment by bitsundae** [comment]
Should I define a new help command to capitalize the flag description or update each flag description manually?

**Comment by christophenne** [comment]
@bitsundae updating all the descriptions manually will be fine. Please look into all commands in `cmd/glasskube/cmd/` and check all descriptions of commands, flags and arguments.
