### ISSUE TITLE
Bootstrap Stuck on 96% (Applying glasskube (PackageRepository))

### ISSUE THREAD

**Issue by eefret** [glasskube/glasskube#948]
**Describe the bug**
Cant get to bootstrap glasskube, I'm using an EKS cluster with Fargate nodes, tried purging and reinstalling.

**To Reproduce**
1. Create an EKS cluster
2. glasskube bootstrap

**Expected behavior**
Should complete bootstrap

**Screenshots**
![image](https://github.com/glasskube/glasskube/assets/863005/49551a12-9c93-4652-8b7b-ae0ba422f64a)

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.28.9-eks-036c24b
 - Provider: AWS

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.12.1
 - CLI version: v0.12.1

**Additional context**
kubectl get nodes -o wide
![image](https://github.com/glasskube/glasskube/assets/863005/745edb8a-54b6-446d-a03e-5953d02739d7)

**Comment by pmig** [comment]
Thanks for raising this issue. Glasskube currently internally uses the Flux `helm-controller`. This is not yet well documented (https://github.com/glasskube/glasskube/issues/917). In this case you would need to bootstrap Glasskube in the `--type=slim` version (https://glasskube.dev/docs/getting-started/bootstrap/).

Can this be also the case in your cluster?

**Comment by kosmoz** [comment]
Hey @eefret, could you please let us know the output of `kubectl describe pods -n glasskube-system`? That might help us finding the issue here.

**Comment by kosmoz** [comment]
Ah I see, that would explain the problem! 

Since I don't think this is something we can solve in the general sense, we should add a "Common issues" section to the docs and explain it there.
