### ISSUE TITLE
Improve website blog layout

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#949]
**Is your feature request related to a problem? Please describe.**
Currently our blog layout is basically the default one and not really appealing.

**Describe the solution you'd like**
After the introduction of  https://github.com/glasskube/glasskube/pull/874 and the image attribute for blog posts, we can also revamp our `/blog` page. Headlamp (also built with Docusaurus) has a very very nice Design we should get a lot of inspiration from: https://headlamp.dev/blog

**Additional context**
@jakepage91 might be needed to add the image attribute to all past blog posts.

**Comment by Baalekshan** [comment]
@pmig Seems like a interesting task. Can I work on this?

**Comment by Baalekshan** [comment]
Sure @kosmoz , I hadn't started yet. But will do shortly.

**Comment by kosmoz** [comment]
Hey @Baalekshan

As discussed via Discord, I've removed your assignment for this issue.

**Comment by Baalekshan** [comment]
Yes @kosmoz , and I need a some other issues to work on. Could you suggest some, I don't see much unassigned help wanted issues. If you could point out something that needs attention, it would be better for me.

**Comment by sratslla** [comment]
Hi @pmig is this issue up for grabs?

**Comment by pmig** [comment]
@sratslla this issue is a typescript / docusaurus task. do you have experiences in this field?

**Comment by sratslla** [comment]
Yes I have lots of experience in web development.

**Comment by pmig** [comment]
Awesome to hear :-) go ahead.

**Comment by kosmoz** [comment]
HEy @sratslla, how are you doing? Do you need any help with this issue?

**Comment by sratslla** [comment]
Hi @kosmoz, I've been swamped with work and haven't had a chance to contribute to open-source recently. If someone else wants to take this up, they're welcome to. Otherwise, I'll get back to it in about a week or two. Apologies for holding up the issue.
