### ISSUE TITLE
Do not consider empty documents when parsing YAMLs

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#952]
**Is your feature request related to a problem? Please describe.**
Some external manifest files might have empty documents, see e.g. https://github.com/glasskube/packages/pull/155. The repo client tries to parse them to unstructured objects, but fails because mandatory fields are missing.

**Describe the solution you'd like**
Ignore empty documents. 

**Additional context**
This blocks https://github.com/glasskube/packages/pull/155.

**Comment by kosmoz** [comment]
Some clarification: I think _parsing_ the emtpy document doesn't fail, but when we try to apply this "empty" `unstructured.Unstructured` instance there is an error.

I think something like this should work:
```go
if len(object.Object) == 0 {
	// object is empty ...
}
```

**Comment by aminsaedi** [comment]
can I take it?

**Comment by pmig** [comment]
@aminsaedi yeah just assigned it to you
