### ISSUE TITLE
UI Footer version messages might be misleading

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#979]
**Is your feature request related to a problem? Please describe.**
The UI footer shows "Up to date", even though there is a newer glasskube version available. The meaning of "Up to date" is that the CLI and cluster version is equal. If they are not equal, the message "New version available" is shown – additionally there is the big update banner at the top of the page. 

**Describe the solution you'd like**
I suggest to remove the extra text like "Up to date" and "New version available" completely, because "Up to date" might be wrong/misleading (it does not mean the user has the latest glasskube version installed right now), and "New version available" is redundant (but more inexact) than the update banner that is on the top of the page anyway. 

We could additionally show a line with "Latest version available: ..." with a link to the release page, and a yellow warning sign that a new version is available (but that shouldn't be too pushy, we already show this when starting the server and in all cli commands too). 

Open for discussion. 

**Describe alternatives you've considered**

**Additional context**

CLI == cluster:
![Screenshot from 2024-07-09 16-01-49](https://github.com/glasskube/glasskube/assets/7556574/2d0d8ab5-e2e2-44f8-8d8f-a4a19d026379)

CLI > cluster: 
![image](https://github.com/glasskube/glasskube/assets/7556574/8301dcc9-2305-4413-8353-59e60af7c00d)

![Screenshot from 2024-07-09 16-09-35](https://github.com/glasskube/glasskube/assets/7556574/f4045bf2-9939-480f-814a-a07bff58610f)

**Comment by bishalbera** [comment]
@christophenne Hello can I take this?

**Comment by christophenne** [comment]
It's still open for discussion what we should do here. What's your take?

**Comment by christophenne** [comment]
We decided that the label should simply be removed in the footer.

**Comment by bishalbera** [comment]
@christophenne Hey really sorry for not replying I was busy learing react 😕 . If the label in the footer needs to be removed can I try that?

> We decided that the label should simply be removed in the footer.
