### ISSUE TITLE
Remove logger dependency from repo client

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#99]
There is a logging-workaround, which should be refactored, see https://github.com/glasskube/glasskube/pull/97#discussion_r1469395170

**Comment by yrs147** [comment]
Hey ! I would like to work on this

**Comment by christophenne** [comment]
@yrs147 all yours :)

**Comment by yrs147** [comment]
Thanks , correct me if I am wrong, but we need to remove the logger dependency from the `pkg/client` dir of the project and replace it with the `fmt` package, right?
